// IgabayCare/src/components/layout/DashboardLayout.tsx
import React, { useState } from 'react';
import { Sidebar } from './Sidebar';
import { Navbar } from './Navbar';
import { PatientNavbar } from './PatientNavbar';
import { ClinicNavbar } from './ClinicNavbar';
import { DoctorNavbar } from './DoctorNavbar';

interface NavigationItem {
  id: string;
  label: string;
  icon: React.ComponentType<{ className?: string }>;
  href?: string;
}

interface DashboardLayoutProps {
  navigationItems: NavigationItem[];
  activeTab: string;
  onTabChange: (tabId: string) => void;
  user: any;
  onSignOut: () => void;
  onSearch?: (query: string) => void;
  variant?: 'patient' | 'clinic' | 'doctor';
  searchPlaceholder?: string;
  showNavbar?: boolean;
  children: React.ReactNode;
}

export const DashboardLayout: React.FC<DashboardLayoutProps> = ({
  navigationItems,
  activeTab,
  onTabChange,
  user,
  onSignOut,
  onSearch,
  variant = 'patient',
  searchPlaceholder,
  showNavbar = false,
  children
}) => {
  const [isSidebarCollapsed, setIsSidebarCollapsed] = useState(false);

  return (
    <div className="min-h-screen bg-gray-50 flex">
      {/* Sidebar */}
      <Sidebar
        navigationItems={navigationItems}
        activeTab={activeTab}
        onTabChange={onTabChange}
        user={user}
        variant={variant}
      />

      {/* Main Content */}
      <div className="flex-1 flex flex-col overflow-hidden transition-all duration-300">
        {/* Navbar - Only show if showNavbar is true */}
        {showNavbar && onSearch && (
          <>
            {variant === 'patient' && (
              <PatientNavbar
                user={user}
                onSearch={onSearch}
                onSignOut={onSignOut}
                activeTab={activeTab}
              />
            )}
            {variant === 'clinic' && (
              <ClinicNavbar
                user={user}
                onSearch={onSearch}
                onSignOut={onSignOut}
                activeTab={activeTab}
              />
            )}
            {variant === 'doctor' && (
              <DoctorNavbar
                user={user}
                onSearch={onSearch}
                onSignOut={onSignOut}
                activeTab={activeTab}
              />
            )}

          </>
        )}

        {/* Page Content */}
        <main className="flex-1 overflow-y-auto bg-gray-50 p-4 lg:p-6">
          <div className="max-w-7xl mx-auto">
            {children}
          </div>
        </main>
      </div>
    </div>
  );
};

// IgabayECare/src/shared/components/layout/DashboardLayout/DashboardLayout.vue
<template>
  <div class="min-h-screen bg-gray-50 flex">
    <!-- Sidebar -->
    <div v-if="showSidebar">
      <slot name="sidebar">
        <DashboardSidebar
          :navigation-items="navigationItems"
          :active-tab="activeTab"
          :user="user"
          :variant="variant"
          :collapsed="sidebarCollapsed"
          :collapsible="sidebarCollapsible"
          @tab-change="handleTabChange"
          @toggle-collapse="handleSidebarToggle"
        />
      </slot>
    </div>

    <!-- Main Content -->
    <div
      class="flex-1 flex flex-col overflow-hidden transition-all duration-300"
      :class="{ 'ml-16': sidebarCollapsed && showSidebar }"
    >
      <!-- Header/Navbar -->
      <div v-if="showNavbar">
        <slot name="header">
          <DashboardNavbar
            :user="user"
            :active-tab="activeTab"
            :search-placeholder="searchPlaceholder"
            :variant="variant"
            :show-search="true"
            @search="handleSearch"
            @sign-out="handleSignOut"
          />
        </slot>
      </div>

      <!-- Page Content -->
      <main :class="mainContentClasses">
        <div :class="containerClasses">
          <slot />
        </div>
      </main>

      <!-- Footer -->
      <div v-if="$slots.footer">
        <slot name="footer" />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue';
import type { DashboardLayoutProps, DashboardLayoutEmits } from './layout.types';
import DashboardSidebar from './DashboardSidebar.vue';
import DashboardNavbar from './DashboardNavbar.vue';

interface Props extends DashboardLayoutProps {}

const props = withDefaults(defineProps<Props>(), {
  variant: 'patient',
  searchPlaceholder: 'Search...',
  showNavbar: true,
  showSidebar: true,
  sidebarCollapsible: true,
  maxWidth: 'full'
});

const emit = defineEmits<DashboardLayoutEmits>();

// Reactive state
const sidebarCollapsed = ref(false);

// Computed classes
const mainContentClasses = computed(() => [
  'flex-1',
  'overflow-y-auto',
  'bg-gray-50',
  'p-4',
  'lg:p-6'
]);

const containerClasses = computed(() => {
  const maxWidthClasses = {
    sm: 'max-w-sm',
    md: 'max-w-md',
    lg: 'max-w-4xl',
    xl: 'max-w-6xl',
    '2xl': 'max-w-7xl',
    full: 'w-full'
  };

  return [
    maxWidthClasses[props.maxWidth],
    'mx-auto'
  ];
});

// Event handlers
const handleTabChange = (tabId: string) => {
  emit('tab-change', tabId);
};

const handleSignOut = () => {
  emit('sign-out');
};

const handleSearch = (query: string) => {
  emit('search', query);
};

const handleSidebarToggle = (collapsed: boolean) => {
  sidebarCollapsed.value = collapsed;
  emit('sidebar-toggle', collapsed);
};
</script>
