// IgabayCare/src/pages/clinic/ClinicHome.tsx
import React, { useState } from "react";
import {
  Users,
  Calendar,
  TrendingUp,
  Activity,
  Clock,
  Star,
  Building,
  Phone,
  Mail,
  MapPin,
  Settings,
  Bell,
  Award,
  Shield,
  DollarSign,
  UserCheck,
  Eye,
  MoreHorizontal,
} from "lucide-react";

import { Card, CardContent } from "../../components/ui/Card";
import { Button } from "../../components/ui/Button";
import { LatestReviews } from "../../components/dashboard/LatestReviews";
import { Pie } from "react-chartjs-2";
import { Chart as ChartJS, ArcElement, Tooltip, Legend, Title } from "chart.js";
ChartJS.register(ArcElement, Tooltip, Legend, Title);

interface ClinicHomeProps {
  onNavigate: (tab: string) => void;
}

export const ClinicHome: React.FC<ClinicHomeProps> = ({ onNavigate }) => {
  const [hoveredCard, setHoveredCard] = useState<string | null>(null);

  const quickActions = [
    {
      id: "appointments",
      title: "Manage Appointments",
      description: "View and schedule patient appointments",
      icon: Calendar,
      color: "from-blue-500 to-blue-600",
      bgColor: "bg-blue-50",
      iconColor: "text-blue-600",
      action: () => onNavigate("appointments"),
    },
    {
      id: "doctors",
      title: "Manage Doctors",
      description: "Manage your clinic's doctors and medical staff",
      icon: Users,
      color: "from-green-500 to-green-600",
      bgColor: "bg-green-50",
      iconColor: "text-green-600",
      action: () => onNavigate("doctors"),
    },
    {
      id: "patients",
      title: "Registered Patients",
      description: "View and manage registered patient records",
      icon: Users,
      color: "from-purple-500 to-purple-600",
      bgColor: "bg-purple-50",
      iconColor: "text-purple-600",
      action: () => onNavigate("patients"),
    },
  ];

  const recentActivity = [
    {
      id: 1,
      type: "appointment",
      title: "New Appointment",
      description: "John Doe - General Checkup",
      time: "30 minutes ago",
      icon: Calendar,
      color: "text-blue-600",
      bgColor: "bg-blue-100",
    },
    {
      id: 2,
      type: "patient",
      title: "Patient Registered",
      description: "Jane Smith - New patient profile created",
      time: "2 hours ago",
      icon: UserCheck,
      color: "text-green-600",
      bgColor: "bg-green-100",
    },
    {
      id: 3,
      type: "review",
      title: "New Review",
      description: "5-star rating from patient visit",
      time: "1 day ago",
      icon: Star,
      color: "text-yellow-600",
      bgColor: "bg-yellow-100",
    },
  ];

  const stats = [
    {
      title: "Total Patients",
      value: "1,247",
      change: "+12",
      changeType: "positive",
      icon: Users,
      color: "text-blue-600",
      bgColor: "bg-blue-50",
    },
    {
      title: "Today's Appointments",
      value: "23",
      change: "Scheduled",
      changeType: "neutral",
      icon: Calendar,
      color: "text-green-600",
      bgColor: "bg-green-50",
    },
    {
      title: "Average Rating",
      value: "4.8",
      change: "+0.2",
      changeType: "positive",
      icon: Star,
      color: "text-yellow-600",
      bgColor: "bg-yellow-50",
    },
  ];

  return (
    <div className="p-6 max-w-7xl mx-auto">
      {/* Stats Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
        {stats.map((stat, index) => (
          <div
            key={stat.title}
            className={`transform transition-all duration-300 hover:scale-105 hover:shadow-lg cursor-pointer ${
              hoveredCard === stat.title ? "ring-2 ring-secondary-200" : ""
            }`}
            onMouseEnter={() => setHoveredCard(stat.title)}
            onMouseLeave={() => setHoveredCard(null)}
          >
            <Card>
              <CardContent className="p-6">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-sm font-medium text-gray-600 mb-1">
                      {stat.title}
                    </p>
                    <p className="text-2xl font-bold text-gray-900">
                      {stat.value}
                    </p>
                    <p
                      className={`text-xs font-medium ${
                        stat.changeType === "positive"
                          ? "text-green-600"
                          : stat.changeType === "negative"
                            ? "text-red-600"
                            : "text-gray-500"
                      }`}
                    >
                      {stat.change}
                    </p>
                  </div>
                  <div className={`p-3 rounded-full ${stat.bgColor}`}>
                    <stat.icon className={`h-6 w-6 ${stat.color}`} />
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        ))}
      </div>

      {/* Latest Reviews with Pie Chart */}
      <div className="mb-8">
        <div className="flex items-center justify-between mb-6">
          <h2 className="text-2xl font-bold text-gray-900">Latest Reviews</h2>
          <Button
            variant="outline"
            onClick={() => onNavigate("settings")}
            className="text-secondary-600 border-secondary-200 hover:bg-secondary-50"
          >
            View All
          </Button>
        </div>

        <div className="flex flex-col lg:flex-row gap-6">
          {/* Reviews Table */}
          <div className="w-full lg:w-2/3">
            <LatestReviews />
          </div>

          {/* Pie Chart */}
          {/* Pie Chart */}
          <div className="w-full lg:w-1/3 bg-white rounded-lg shadow p-4">
            <h3 className="text-lg font-semibold text-gray-900 mb-4">
              Review Sentiment
            </h3>

            <div
              style={{ position: "relative", height: "250px", width: "100%" }}
            >
              <Pie
                data={{
                  labels: ["Positive", "Negative", "Neutral"],
                  datasets: [
                    {
                      label: "Sentiment",
                      data: [10, 5, 2],
                      backgroundColor: [
                        "rgba(34, 197, 94, 0.5)", // Green
                        "rgba(239, 68, 68, 0.5)", // Red
                        "rgba(234, 179, 8, 0.5)", // Yellow
                      ],
                      borderColor: [
                        "rgba(34, 197, 94, 1)",
                        "rgba(239, 68, 68, 1)",
                        "rgba(234, 179, 8, 1)",
                      ],
                      borderWidth: 1,
                    },
                  ],
                }}
                options={{
                  responsive: true,
                  maintainAspectRatio: false,
                  plugins: {
                    legend: {
                      position: "bottom",
                    },
                    title: {
                      display: false,
                    },
                  },
                }}
              />
            </div>
          </div>
        </div>
      </div>

      {/* Recent Activity */}
      <div className="mt-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-6">
          Recent Activity
        </h2>
        <div className="space-y-4">
          {recentActivity.map((activity) => (
            <Card
              key={activity.id}
              className="group cursor-pointer transform transition-all duration-300 hover:scale-102 hover:shadow-md border-l-4 border-l-transparent hover:border-l-secondary-500"
            >
              <CardContent className="p-4">
                <div className="flex items-center space-x-4">
                  <div
                    className={`p-2 rounded-full ${activity.bgColor} group-hover:scale-110 transition-transform duration-300`}
                  >
                    <activity.icon className={`h-5 w-5 ${activity.color}`} />
                  </div>
                  <div className="flex-1">
                    <h3 className="font-semibold text-gray-900 group-hover:text-secondary-600 transition-colors">
                      {activity.title}
                    </h3>
                    <p className="text-gray-600 text-sm">
                      {activity.description}
                    </p>
                  </div>
                  <div className="text-xs text-gray-500 group-hover:text-gray-700 transition-colors">
                    {activity.time}
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>

      {/* Clinic Performance Promo */}
      <div className="mt-8">
        <Card className="bg-gradient-to-r from-secondary-50 to-blue-50 border-secondary-200">
          <CardContent className="p-6">
            <div className="flex items-center justify-between">
              <div className="flex items-center space-x-4">
                <div className="p-3 bg-gradient-to-r from-secondary-500 to-blue-500 rounded-full">
                  <TrendingUp className="h-6 w-6 text-white" />
                </div>
                <div>
                  <h3 className="text-lg font-semibold text-gray-900">
                    Boost Your Clinic Performance
                  </h3>
                  <p className="text-gray-600">
                    Access detailed analytics and insights to improve patient
                    care
                  </p>
                </div>
              </div>
              <Button
                variant="gradient"
                onClick={() => onNavigate("settings")}
                className="bg-gradient-to-r from-secondary-500 to-blue-500 hover:from-secondary-600 hover:to-blue-600"
              >
                Settings
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
};

// IgabayECare/src/views/clinic/ClinicHome.vue
<script setup lang="ts">
import { ref } from 'vue';
import {
  Users,
  Calendar,
  TrendingUp,
  Activity,
  Clock,
  Star,
  Building,
  Phone,
  Mail,
  MapPin,
  Settings,
  Bell,
  Award,
  Shield,
  DollarSign,
  UserCheck,
  Eye,
  MoreHorizontal,
} from 'lucide-vue-next';

import Card from '../../components/ui/Card.vue';
import Button from '../../components/ui/Button.vue';
import LatestReviews from '../../components/dashboard/LatestReviews.vue';
import { Pie } from 'vue-chartjs';
import { Chart as ChartJS, ArcElement, Tooltip, Legend, Title } from 'chart.js';
ChartJS.register(ArcElement, Tooltip, Legend, Title);

const props = defineProps<{
  onNavigate: (tab: string) => void;
}>();

const hoveredCard = ref<string | null>(null);

const quickActions = [
  {
    id: 'appointments',
    title: 'Manage Appointments',
    description: 'View and schedule patient appointments',
    icon: Calendar,
    color: 'from-blue-500 to-blue-600',
    bgColor: 'bg-blue-50',
    iconColor: 'text-blue-600',
    action: () => props.onNavigate('appointments'),
  },
  {
    id: 'doctors',
    title: 'Manage Doctors',
    description: "Manage your clinic's doctors and medical staff",
    icon: Users,
    color: 'from-green-500 to-green-600',
    bgColor: 'bg-green-50',
    iconColor: 'text-green-600',
    action: () => props.onNavigate('doctors'),
  },
  {
    id: 'patients',
    title: 'Registered Patients',
    description: 'View and manage registered patient records',
    icon: Users,
    color: 'from-purple-500 to-purple-600',
    bgColor: 'bg-purple-50',
    iconColor: 'text-purple-600',
    action: () => props.onNavigate('patients'),
  },
];

const recentActivity = [
  {
    id: 1,
    type: 'appointment',
    title: 'New Appointment',
    description: 'John Doe - General Checkup',
    time: '30 minutes ago',
    icon: Calendar,
    color: 'text-blue-600',
    bgColor: 'bg-blue-100',
  },
  {
    id: 2,
    type: 'patient',
    title: 'Patient Registered',
    description: 'Jane Smith - New patient profile created',
    time: '2 hours ago',
    icon: UserCheck,
    color: 'text-green-600',
    bgColor: 'bg-green-100',
  },
  {
    id: 3,
    type: 'review',
    title: 'New Review',
    description: '5-star rating from patient visit',
    time: '1 day ago',
    icon: Star,
    color: 'text-yellow-600',
    bgColor: 'bg-yellow-100',
  },
];

const appointmentData = {
  labels: ['Completed', 'Scheduled', 'Cancelled'],
  datasets: [
    {
      data: [65, 25, 10],
      backgroundColor: ['#10b981', '#3b82f6', '#ef4444'],
      borderWidth: 0,
    },
  ],
};

const patientData = {
  labels: ['New', 'Returning', 'Referred'],
  datasets: [
    {
      data: [30, 55, 15],
      backgroundColor: ['#3b82f6', '#10b981', '#8b5cf6'],
      borderWidth: 0,
    },
  ],
};

const chartOptions = {
  responsive: true,
  maintainAspectRatio: false,
  plugins: {
    legend: {
      position: 'bottom',
      labels: {
        boxWidth: 12,
        padding: 15,
        font: {
          size: 12,
        },
      },
    },
  },
};

const stats = [
  {
    title: 'Total Appointments',
    value: '128',
    change: '+12%',
    trend: 'up',
    icon: Calendar,
    color: 'text-blue-600',
    bgColor: 'bg-blue-100',
  },
  {
    title: 'Active Doctors',
    value: '24',
    change: '+2',
    trend: 'up',
    icon: Users,
    color: 'text-green-600',
    bgColor: 'bg-green-100',
  },
  {
    title: 'Patient Satisfaction',
    value: '4.8',
    change: '+0.2',
    trend: 'up',
    icon: Star,
    color: 'text-yellow-600',
    bgColor: 'bg-yellow-100',
  },
  {
    title: 'Avg. Wait Time',
    value: '12m',
    change: '-2m',
    trend: 'down',
    icon: Clock,
    color: 'text-purple-600',
    bgColor: 'bg-purple-100',
  },
];

const clinicInfo = {
  name: 'MediClinic Central',
  address: '123 Healthcare Ave, Medical District',
  phone: '+1 (555) 123-4567',
  email: 'info@mediclinic.com',
  hours: 'Mon-Fri: 8am-6pm, Sat: 9am-2pm',
  specialties: ['General Medicine', 'Pediatrics', 'Cardiology', 'Orthopedics'],
};
</script>

<template>
  <div class="p-6 space-y-6">
    <div class="flex flex-col md:flex-row justify-between items-start md:items-center mb-6">
      <div>
        <h1 class="text-2xl font-bold text-gray-900">Clinic Dashboard</h1>
        <p class="text-gray-600">Welcome back to your clinic management portal</p>
      </div>
      <div class="mt-4 md:mt-0 flex space-x-2">
        <Button variant="outline" class="flex items-center gap-2">
          <Bell class="h-4 w-4" />
          Notifications
        </Button>
        <Button variant="default" class="flex items-center gap-2" @click="props.onNavigate('settings')">
          <Settings class="h-4 w-4" />
          Settings
        </Button>
      </div>
    </div>

    <!-- Quick Actions -->
    <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
      <div
        v-for="action in quickActions"
        :key="action.id"
        class="relative overflow-hidden rounded-lg shadow-sm transition-all duration-300 hover:shadow-md"
        :class="{ 'ring-2 ring-offset-2 ring-blue-500': hoveredCard === action.id }"
        @mouseenter="hoveredCard = action.id"
        @mouseleave="hoveredCard = null"
        @click="action.action"
      >
        <div
          class="absolute inset-0 opacity-0 transition-opacity duration-300"
          :class="{ 'opacity-100': hoveredCard === action.id }"
        >
          <div class="absolute inset-0 bg-gradient-to-r" :class="action.color"></div>
        </div>

        <Card class="h-full border-0 bg-white relative z-10 transition-colors duration-300" :class="{
          'bg-opacity-90 text-white': hoveredCard === action.id,
        }">
          <CardContent class="p-6">
            <div class="flex items-start space-x-4">
              <div
                class="p-3 rounded-full"
                :class="hoveredCard === action.id ? 'bg-white bg-opacity-20' : action.bgColor"
              >
                <component
                  :is="action.icon"
                  class="h-6 w-6"
                  :class="hoveredCard === action.id ? 'text-white' : action.iconColor"
                />
              </div>
              <div class="flex-1">
                <h3 class="text-lg font-semibold mb-1" :class="{
                  'text-white': hoveredCard === action.id,
                  'text-gray-900': hoveredCard !== action.id,
                }">
                  {{ action.title }}
                </h3>
                <p
                  class="text-sm"
                  :class="{
                    'text-white text-opacity-90': hoveredCard === action.id,
                    'text-gray-600': hoveredCard !== action.id,
                  }"
                >
                  {{ action.description }}
                </p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>

    <!-- Stats Row -->
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
      <Card v-for="stat in stats" :key="stat.title" class="border-0 shadow-sm">
        <CardContent class="p-4">
          <div class="flex justify-between items-start">
            <div>
              <p class="text-sm font-medium text-gray-500">{{ stat.title }}</p>
              <div class="flex items-baseline mt-1">
                <h3 class="text-2xl font-bold text-gray-900">{{ stat.value }}</h3>
                <span
                  class="ml-2 text-sm font-medium"
                  :class="{
                    'text-green-600': stat.trend === 'up',
                    'text-red-600': stat.trend === 'down',
                  }"
                >
                  {{ stat.change }}
                </span>
              </div>
            </div>
            <div :class="`p-2 rounded-full ${stat.bgColor}`">
              <component :is="stat.icon" class="h-5 w-5" :class="stat.color" />
            </div>
          </div>
        </CardContent>
      </Card>
    </div>

    <!-- Charts and Activity -->
    <div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
      <!-- Appointment Distribution -->
      <Card class="border-0 shadow-sm col-span-1">
        <CardContent class="p-6">
          <div class="flex justify-between items-center mb-4">
            <h3 class="text-lg font-semibold text-gray-900">Appointment Status</h3>
            <Button variant="ghost" size="sm" class="text-gray-500 hover:text-gray-700">
              <MoreHorizontal class="h-4 w-4" />
            </Button>
          </div>
          <div class="h-64">
            <Pie :data="appointmentData" :options="chartOptions" />
          </div>
        </CardContent>
      </Card>

      <!-- Patient Distribution -->
      <Card class="border-0 shadow-sm col-span-1">
        <CardContent class="p-6">
          <div class="flex justify-between items-center mb-4">
            <h3 class="text-lg font-semibold text-gray-900">Patient Distribution</h3>
            <Button variant="ghost" size="sm" class="text-gray-500 hover:text-gray-700">
              <MoreHorizontal class="h-4 w-4" />
            </Button>
          </div>
          <div class="h-64">
            <Pie :data="patientData" :options="chartOptions" />
          </div>
        </CardContent>
      </Card>

      <!-- Recent Activity -->
      <Card class="border-0 shadow-sm col-span-1">
        <CardContent class="p-6">
          <div class="flex justify-between items-center mb-4">
            <h3 class="text-lg font-semibold text-gray-900">Recent Activity</h3>
            <Button variant="ghost" size="sm" class="text-gray-500 hover:text-gray-700">
              <Eye class="h-4 w-4" />
              View All
            </Button>
          </div>
          <div class="space-y-4">
            <div v-for="activity in recentActivity" :key="activity.id" class="flex items-start space-x-3">
              <div :class="`p-2 rounded-full ${activity.bgColor}`">
                <component :is="activity.icon" class="h-4 w-4" :class="activity.color" />
              </div>
              <div class="flex-1">
                <div class="flex justify-between items-start">
                  <h4 class="text-sm font-medium text-gray-900">{{ activity.title }}</h4>
                  <span class="text-xs text-gray-500">{{ activity.time }}</span>
                </div>
                <p class="text-sm text-gray-600">{{ activity.description }}</p>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>

    <!-- Clinic Info -->
    <Card class="border-0 shadow-sm">
      <CardContent class="p-6">
        <div class="flex justify-between items-center mb-4">
          <h3 class="text-lg font-semibold text-gray-900">Clinic Information</h3>
          <Button
            variant="outline"
            size="sm"
            class="text-blue-600 border-blue-200 hover:bg-blue-50"
            @click="props.onNavigate('manage')"
          >
            <Settings class="h-4 w-4 mr-1" />
            Manage
          </Button>
        </div>

        <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div class="space-y-4">
            <div class="flex items-start space-x-3">
              <div class="p-2 rounded-full bg-blue-100 text-blue-600">
                <Building class="h-5 w-5" />
              </div>
              <div>
                <p class="text-sm font-medium text-gray-500">Clinic Name</p>
                <p class="text-base text-gray-900">{{ clinicInfo.name }}</p>
              </div>
            </div>

            <div class="flex items-start space-x-3">
              <div class="p-2 rounded-full bg-blue-100 text-blue-600">
                <MapPin class="h-5 w-5" />
              </div>
              <div>
                <p class="text-sm font-medium text-gray-500">Address</p>
                <p class="text-base text-gray-900">{{ clinicInfo.address }}</p>
              </div>
            </div>

            <div class="flex items-start space-x-3">
              <div class="p-2 rounded-full bg-blue-100 text-blue-600">
                <Phone class="h-5 w-5" />
              </div>
              <div>
                <p class="text-sm font-medium text-gray-500">Phone</p>
                <p class="text-base text-gray-900">{{ clinicInfo.phone }}</p>
              </div>
            </div>
          </div>

          <div class="space-y-4">
            <div class="flex items-start space-x-3">
              <div class="p-2 rounded-full bg-blue-100 text-blue-600">
                <Mail class="h-5 w-5" />
              </div>
              <div>
                <p class="text-sm font-medium text-gray-500">Email</p>
                <p class="text-base text-gray-900">{{ clinicInfo.email }}</p>
              </div>
            </div>

            <div class="flex items-start space-x-3">
              <div class="p-2 rounded-full bg-blue-100 text-blue-600">
                <Clock class="h-5 w-5" />
              </div>
              <div>
                <p class="text-sm font-medium text-gray-500">Operating Hours</p>
                <p class="text-base text-gray-900">{{ clinicInfo.hours }}</p>
              </div>
            </div>

            <div class="flex items-start space-x-3">
              <div class="p-2 rounded-full bg-blue-100 text-blue-600">
                <Award class="h-5 w-5" />
              </div>
              <div>
                <p class="text-sm font-medium text-gray-500">Specialties</p>
                <div class="flex flex-wrap gap-2 mt-1">
                  <span
                    v-for="specialty in clinicInfo.specialties"
                    :key="specialty"
                    class="px-2 py-1 text-xs font-medium bg-blue-50 text-blue-700 rounded-full"
                  >
                    {{ specialty }}
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  </div>
</template>
