// IgabayCare/src/pages/clinic/ClinicDashboard.tsx
import React, { useState, useEffect } from 'react';
import { Home, Calendar, Users, UserCheck, Settings,UserCircle  } from 'lucide-react';
import { DashboardLayout } from '../../components/layout/DashboardLayout';
import { ClinicHome } from './ClinicHome';
import { ClinicAppointments } from '../../components/clinic/ClinicAppointments';
import { ClinicDoctors } from './ClinicDoctors';
import { ClinicPatients } from './ClinicPatients';
import { ClinicSettings } from './ClinicSettings';
import { Appointment } from './Appointment';
import { ManageClinic } from './ManageClinic';
import { roleBasedAuthService } from '../../features/auth/utils/roleBasedAuthService';
import { useNavigate } from 'react-router-dom';
import { SkeletonDashboard } from '../../components/ui/Skeleton';



export const ClinicDashboard: React.FC = () => {
  const [activeTab, setActiveTab] = useState('dashboard');
  const [user, setUser] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const navigate = useNavigate();

  useEffect(() => {
    const checkAuth = async () => {
      try {
        const currentUser = await roleBasedAuthService.getCurrentUser();
        if (!currentUser || currentUser.role !== 'clinic') {
          navigate('/clinic-signin');
          return;
        }
        setUser(currentUser);
      } catch (error) {
        console.error('Auth check error:', error);
        navigate('/clinic-signin');
      } finally {
        setLoading(false);
      }
    };

    checkAuth();
  }, [navigate]);

  const navigationItems = [
    { id: 'dashboard', label: 'Dashboard', icon: Home },
    { id: 'appointments', label: 'Appointments', icon: Calendar },
    { id: 'doctors', label: 'Doctors', icon: Users },
    // { id: 'patients', label: 'Registered Patients', icon: UserCheck },
    { id: 'manage', label: 'Manage Clinic', icon: Settings },
    { id: 'settings', label: 'Profile', icon: UserCircle  },
  ];

  const handleSignOut = async () => {
    try {
      const result = await roleBasedAuthService.signOut();
      if (result.success) {
        // Redirect to landing page after successful sign out
        navigate('/');
      } else {
        console.error('Sign out failed:', result.error);
        // Still redirect even if there's an error
        navigate('/');
      }
    } catch (error) {
      console.error('Error during sign out:', error);
      // Redirect to landing page even if there's an error
      navigate('/');
    }
  };

  const handleSearch = (query: string) => {
    // TODO: Implement search functionality for clinic dashboard
    console.log('Clinic search query:', query);
  };

  const renderContent = () => {
    switch (activeTab) {
      case 'dashboard':
        return <ClinicHome onNavigate={setActiveTab} />;
      case 'appointments':
        return <Appointment clinicId={user?.clinic_id || ''} />;
      case 'doctors':
        return <ClinicDoctors />;
      case 'patients':
        return <ClinicPatients />;
      case 'manage':
        return <ManageClinic />;
      case 'settings':
        return <ClinicSettings />;
      default:
        return <ClinicHome onNavigate={setActiveTab} />;
    }
  };

  if (loading) {
    return <SkeletonDashboard />;
  }

  return (
    <DashboardLayout
      navigationItems={navigationItems}
      activeTab={activeTab}
      onTabChange={setActiveTab}
      user={user}
      onSignOut={handleSignOut}
      onSearch={handleSearch}
      variant="clinic"
      searchPlaceholder="Search patients, appointments, or reports..."
      showNavbar={true}
    >
      {renderContent()}
    </DashboardLayout>
  );
};

// IgabayECare/src/views/clinic/ClinicDashboard.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { useRouter } from 'vue-router';
import { Home, Calendar, Users, Settings, UserCircle } from 'lucide-vue-next';
import DashboardLayout from '../../shared/components/layout/DashboardLayout/DashboardLayout.vue';
import ClinicHome from './ClinicHome.vue';
import ClinicDoctors from './ClinicDoctors.vue';
import ClinicPatients from './ClinicPatients.vue';
import ClinicSettings from './ClinicSettings.vue';
import Appointment from './Appointment.vue';
import ManageClinic from './ManageClinic.vue';
import { AuthService } from '../../modules/auth/services/AuthService';
import SkeletonDashboard from '../../shared/components/ui/Skeleton/Skeleton.vue';

const activeTab = ref('dashboard');
const user = ref<{ id?: string; name?: string; email?: string; role?: string; clinic_id?: string; avatar?: string } | null>(null);
const loading = ref(true);
const router = useRouter();
const authService = new AuthService();

onMounted(async () => {
  await checkAuth();
});

const checkAuth = async () => {
  try {
    const currentUser = await authService.getCurrentUser();
    if (!currentUser || currentUser.role !== 'clinic') {
      router.push('/clinic-signin');
      return;
    }
    user.value = currentUser;
  } catch (error) {
    console.error('Auth check error:', error);
    router.push('/clinic-signin');
  } finally {
    loading.value = false;
  }
};

const navigationItems = [
  { id: 'dashboard', label: 'Dashboard', icon: Home },
  { id: 'appointments', label: 'Appointments', icon: Calendar },
  { id: 'doctors', label: 'Doctors', icon: Users },
  // { id: 'patients', label: 'Registered Patients', icon: UserCheck },
  { id: 'manage', label: 'Manage Clinic', icon: Settings },
  { id: 'settings', label: 'Profile', icon: UserCircle },
];

const handleSignOut = async () => {
  try {
    const result = await authService.signOut();
    if (result.success) {
      // Redirect to landing page after successful sign out
      router.push('/');
    } else {
      console.error('Sign out failed:', result.error);
      // Still redirect even if there's an error
      router.push('/');
    }
  } catch (error) {
    console.error('Error during sign out:', error);
    // Redirect to landing page even if there's an error
    router.push('/');
  }
};

const handleSearch = (query: string) => {
  // TODO: Implement search functionality for clinic dashboard
  console.log('Clinic search query:', query);
};

const setActiveTab = (tab: string) => {
  activeTab.value = tab;
};
</script>

<template>
  <SkeletonDashboard v-if="loading" />
  <DashboardLayout
    v-else
    :navigationItems="navigationItems"
    :activeTab="activeTab"
    @tabChange="setActiveTab"
    @signOut="handleSignOut"
    @search="handleSearch"
    :userName="user?.name || 'Clinic Admin'"
    :userRole="'Clinic Administrator'"
    :userAvatar="user?.avatar || ''"
  >
    <component
      :is="activeTab === 'dashboard' ? ClinicHome :
           activeTab === 'appointments' ? Appointment :
           activeTab === 'doctors' ? ClinicDoctors :
           activeTab === 'patients' ? ClinicPatients :
           activeTab === 'manage' ? ManageClinic :
           activeTab === 'settings' ? ClinicSettings : ClinicHome"
      :onNavigate="setActiveTab"
      :clinicId="user?.clinic_id || ''"
    />
  </DashboardLayout>
</template>
