// project/src/components/clinic/ClinicSettings.tsx
import React, { useState } from 'react';
import { Save, Camera, Clock, DollarSign, Shield, Bell } from 'lucide-react';
import { Button } from '../ui/Button';
import { Input } from '../ui/Input';
import { Card, CardContent, CardHeader } from '../ui/Card';

export const ClinicSettings: React.FC = () => {
  const [isEditing, setIsEditing] = useState(false);
  const [clinicData, setClinicData] = useState({
    clinicName: 'City General Hospital',
    address: '123 Main Street, Downtown, City 12345',
    phone: '+1 234-567-8900',
    email: 'info@citygeneralhospital.com',
    website: 'www.citygeneralhospital.com',
    license: 'MED-12345-2024',
    accreditation: 'ACC-98765-2024',
    description: 'A modern healthcare facility providing comprehensive medical services to the community.',
    services: ['General Medicine', 'Emergency Care', 'Preventive Care', 'Laboratory Services'],
    operatingHours: {
      monday: { open: '08:00', close: '18:00' },
      tuesday: { open: '08:00', close: '18:00' },
      wednesday: { open: '08:00', close: '18:00' },
      thursday: { open: '08:00', close: '18:00' },
      friday: { open: '08:00', close: '18:00' },
      saturday: { open: '09:00', close: '16:00' },
      sunday: { open: '10:00', close: '14:00' },
    },
    paymentBeforeBooking: true,
    emailNotifications: true,
    smsNotifications: false,
    bookingConfirmation: true,
    autoValidation: true,
  });

  const handleSave = () => {
    // TODO: Save to Supabase
    setIsEditing(false);
  };

  const handleInputChange = (field: string, value: any) => {
    setClinicData(prev => ({ ...prev, [field]: value }));
  };

  const handleOperatingHoursChange = (day: string, field: 'open' | 'close', value: string) => {
    setClinicData(prev => ({
      ...prev,
      operatingHours: {
        ...prev.operatingHours,
        [day]: {
          ...prev.operatingHours[day as keyof typeof prev.operatingHours],
          [field]: value
        }
      }
    }));
  };

  const days = [
    { key: 'monday', label: 'Monday' },
    { key: 'tuesday', label: 'Tuesday' },
    { key: 'wednesday', label: 'Wednesday' },
    { key: 'thursday', label: 'Thursday' },
    { key: 'friday', label: 'Friday' },
    { key: 'saturday', label: 'Saturday' },
    { key: 'sunday', label: 'Sunday' },
  ];

  return (
    <div className="p-6">
      <div className="flex justify-between items-center mb-6">
        <div>
          <h1 className="text-3xl font-bold text-gray-900 mb-2">Clinic Settings</h1>
          <p className="text-gray-600">Manage your clinic's information and preferences</p>
        </div>
        <Button
          onClick={() => isEditing ? handleSave() : setIsEditing(true)}
        >
          {isEditing ? (
            <>
              <Save size={16} className="mr-2" />
              Save Changes
            </>
          ) : (
            'Edit Settings'
          )}
        </Button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Profile Section */}
        <div className="lg:col-span-1 space-y-6">
          {/* Clinic Logo */}
          <Card>
            <CardContent className="p-6 text-center">
              <div className="relative inline-block mb-4">
                <div className="w-32 h-32 bg-gray-200 rounded-lg flex items-center justify-center mx-auto">
                  <div className="text-center">
                    <Camera size={32} className="text-gray-400 mx-auto mb-2" />
                    <p className="text-sm text-gray-500">Clinic Logo</p>
                  </div>
                </div>
                {isEditing && (
                  <button className="absolute bottom-0 right-0 bg-blue-600 text-white p-2 rounded-full hover:bg-blue-700 transition-colors">
                    <Camera size={16} />
                  </button>
                )}
              </div>
              <h3 className="text-xl font-semibold text-gray-900">{clinicData.clinicName}</h3>
              <p className="text-gray-600">{clinicData.email}</p>
            </CardContent>
          </Card>

          {/* Quick Stats */}
          <Card>
            <CardHeader>
              <h3 className="text-lg font-semibold text-gray-900">Quick Stats</h3>
            </CardHeader>
            <CardContent className="pt-0">
              <div className="space-y-3">
                <div className="flex justify-between">
                  <span className="text-gray-600">Total Doctors</span>
                  <span className="font-medium">3</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-gray-600">Total Patients</span>
                  <span className="font-medium">1,247</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-gray-600">This Month</span>
                  <span className="font-medium">69 appointments</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-gray-600">Status</span>
                  <span className="px-2 py-1 bg-green-100 text-green-800 text-sm font-medium rounded-full">
                    Verified
                  </span>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Main Settings */}
        <div className="lg:col-span-2 space-y-6">
          {/* Basic Information */}
          <Card>
            <CardHeader>
              <h3 className="text-lg font-semibold text-gray-900">Basic Information</h3>
            </CardHeader>
            <CardContent className="pt-0 space-y-4">
              <Input
                label="Clinic Name"
                value={clinicData.clinicName}
                onChange={(e) => handleInputChange('clinicName', e.target.value)}
                disabled={!isEditing}
              />
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <Input
                  label="Phone Number"
                  value={clinicData.phone}
                  onChange={(e) => handleInputChange('phone', e.target.value)}
                  disabled={!isEditing}
                />
                <Input
                  label="Email Address"
                  type="email"
                  value={clinicData.email}
                  onChange={(e) => handleInputChange('email', e.target.value)}
                  disabled={!isEditing}
                />
              </div>

              <Input
                label="Website"
                value={clinicData.website}
                onChange={(e) => handleInputChange('website', e.target.value)}
                disabled={!isEditing}
              />

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Address</label>
                <textarea
                  value={clinicData.address}
                  onChange={(e) => handleInputChange('address', e.target.value)}
                  disabled={!isEditing}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:bg-gray-50"
                  rows={2}
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Description</label>
                <textarea
                  value={clinicData.description}
                  onChange={(e) => handleInputChange('description', e.target.value)}
                  disabled={!isEditing}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:bg-gray-50"
                  rows={3}
                />
              </div>
            </CardContent>
          </Card>

          {/* License & Accreditation */}
          <Card>
            <CardHeader>
              <div className="flex items-center space-x-2">
                <Shield className="text-blue-600" size={20} />
                <h3 className="text-lg font-semibold text-gray-900">License & Accreditation</h3>
              </div>
            </CardHeader>
            <CardContent className="pt-0">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <Input
                  label="Medical License Number"
                  value={clinicData.license}
                  onChange={(e) => handleInputChange('license', e.target.value)}
                  disabled={!isEditing}
                />
                <Input
                  label="Accreditation Number"
                  value={clinicData.accreditation}
                  onChange={(e) => handleInputChange('accreditation', e.target.value)}
                  disabled={!isEditing}
                />
              </div>
            </CardContent>
          </Card>

          {/* Operating Hours */}
          <Card>
            <CardHeader>
              <div className="flex items-center space-x-2">
                <Clock className="text-green-600" size={20} />
                <h3 className="text-lg font-semibold text-gray-900">Operating Hours</h3>
              </div>
            </CardHeader>
            <CardContent className="pt-0">
              <div className="space-y-3">
                {days.map((day) => (
                  <div key={day.key} className="flex items-center space-x-4 p-3 bg-gray-50 rounded-lg">
                    <div className="w-24 text-sm font-medium text-gray-900">
                      {day.label}
                    </div>
                    <Input
                      type="time"
                      value={clinicData.operatingHours[day.key as keyof typeof clinicData.operatingHours].open}
                      onChange={(e) => handleOperatingHoursChange(day.key, 'open', e.target.value)}
                      disabled={!isEditing}
                      className="flex-1"
                    />
                    <div className="text-gray-500">to</div>
                    <Input
                      type="time"
                      value={clinicData.operatingHours[day.key as keyof typeof clinicData.operatingHours].close}
                      onChange={(e) => handleOperatingHoursChange(day.key, 'close', e.target.value)}
                      disabled={!isEditing}
                      className="flex-1"
                    />
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>

          {/* Booking Settings */}
          <Card>
            <CardHeader>
              <div className="flex items-center space-x-2">
                <DollarSign className="text-purple-600" size={20} />
                <h3 className="text-lg font-semibold text-gray-900">Booking Settings</h3>
              </div>
            </CardHeader>
            <CardContent className="pt-0">
              <div className="space-y-4">
                <div className="flex items-center justify-between p-4 bg-gray-50 rounded-lg">
                  <div>
                    <h4 className="font-medium text-gray-900">Payment Before Booking</h4>
                    <p className="text-sm text-gray-600">Require patients to pay before confirming appointments</p>
                  </div>
                  <button 
                    onClick={() => handleInputChange('paymentBeforeBooking', !clinicData.paymentBeforeBooking)}
                    disabled={!isEditing}
                    className={`w-12 h-6 rounded-full transition-colors ${
                      clinicData.paymentBeforeBooking ? 'bg-blue-600' : 'bg-gray-300'
                    }`}
                  >
                    <div className={`bg-white w-5 h-5 rounded-full transition-transform ${
                      clinicData.paymentBeforeBooking ? 'translate-x-6' : 'translate-x-0.5'
                    }`}></div>
                  </button>
                </div>

                <div className="flex items-center justify-between p-4 bg-gray-50 rounded-lg">
                  <div>
                    <h4 className="font-medium text-gray-900">Automated Validation</h4>
                    <p className="text-sm text-gray-600">Use ML to validate bookings and prevent fraud</p>
                  </div>
                  <button 
                    onClick={() => handleInputChange('autoValidation', !clinicData.autoValidation)}
                    disabled={!isEditing}
                    className={`w-12 h-6 rounded-full transition-colors ${
                      clinicData.autoValidation ? 'bg-blue-600' : 'bg-gray-300'
                    }`}
                  >
                    <div className={`bg-white w-5 h-5 rounded-full transition-transform ${
                      clinicData.autoValidation ? 'translate-x-6' : 'translate-x-0.5'
                    }`}></div>
                  </button>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Notification Settings */}
          <Card>
            <CardHeader>
              <div className="flex items-center space-x-2">
                <Bell className="text-orange-600" size={20} />
                <h3 className="text-lg font-semibold text-gray-900">Notification Settings</h3>
              </div>
            </CardHeader>
            <CardContent className="pt-0">
              <div className="space-y-4">
                <div className="flex items-center justify-between p-4 bg-gray-50 rounded-lg">
                  <div>
                    <h4 className="font-medium text-gray-900">Email Notifications</h4>
                    <p className="text-sm text-gray-600">Receive appointment updates via email</p>
                  </div>
                  <button 
                    onClick={() => handleInputChange('emailNotifications', !clinicData.emailNotifications)}
                    disabled={!isEditing}
                    className={`w-12 h-6 rounded-full transition-colors ${
                      clinicData.emailNotifications ? 'bg-blue-600' : 'bg-gray-300'
                    }`}
                  >
                    <div className={`bg-white w-5 h-5 rounded-full transition-transform ${
                      clinicData.emailNotifications ? 'translate-x-6' : 'translate-x-0.5'
                    }`}></div>
                  </button>
                </div>

                <div className="flex items-center justify-between p-4 bg-gray-50 rounded-lg">
                  <div>
                    <h4 className="font-medium text-gray-900">SMS Notifications</h4>
                    <p className="text-sm text-gray-600">Receive text message notifications</p>
                  </div>
                  <button 
                    onClick={() => handleInputChange('smsNotifications', !clinicData.smsNotifications)}
                    disabled={!isEditing}
                    className={`w-12 h-6 rounded-full transition-colors ${
                      clinicData.smsNotifications ? 'bg-blue-600' : 'bg-gray-300'
                    }`}
                  >
                    <div className={`bg-white w-5 h-5 rounded-full transition-transform ${
                      clinicData.smsNotifications ? 'translate-x-6' : 'translate-x-0.5'
                    }`}></div>
                  </button>
                </div>

                <div className="flex items-center justify-between p-4 bg-gray-50 rounded-lg">
                  <div>
                    <h4 className="font-medium text-gray-900">Booking Confirmations</h4>
                    <p className="text-sm text-gray-600">Send confirmation notifications for new bookings</p>
                  </div>
                  <button 
                    onClick={() => handleInputChange('bookingConfirmation', !clinicData.bookingConfirmation)}
                    disabled={!isEditing}
                    className={`w-12 h-6 rounded-full transition-colors ${
                      clinicData.bookingConfirmation ? 'bg-blue-600' : 'bg-gray-300'
                    }`}
                  >
                    <div className={`bg-white w-5 h-5 rounded-full transition-transform ${
                      clinicData.bookingConfirmation ? 'translate-x-6' : 'translate-x-0.5'
                    }`}></div>
                  </button>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
};

// IgabayECare/src/views/clinic/ClinicSettings.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { Save, Camera, Clock, DollarSign, Shield, Bell, Edit, Loader2, AlertTriangle } from 'lucide-vue-next';
import Button from '../../components/ui/Button.vue';
import Input from '../../components/ui/Input.vue';
import { Card, CardContent, CardHeader } from '../../components/ui/Card.vue';
import { roleBasedAuthService } from '../../features/auth/utils/roleBasedAuthService';
import { clinicService, type ClinicProfile } from '../../features/auth/utils/clinicService';

const isEditing = ref(false);
const isSaving = ref(false);
const isLoading = ref(true);
const error = ref<string | null>(null);

const clinicData = ref<ClinicProfile>({
  id: '',
  user_id: '',
  clinic_name: '',
  email: '',
  phone: '',
  website: '',
  address: '',
  city: '',
  state: '',
  zip_code: '',
  license_number: '',
  accreditation: '',
  tax_id: '',
  year_established: undefined,
  specialties: [],
  custom_specialties: [],
  services: [],
  custom_services: [],
  operating_hours: {
    monday: { open: '08:00', close: '18:00' },
    tuesday: { open: '08:00', close: '18:00' },
    wednesday: { open: '08:00', close: '18:00' },
    thursday: { open: '08:00', close: '18:00' },
    friday: { open: '08:00', close: '18:00' },
    saturday: { open: '09:00', close: '16:00' },
    sunday: { open: '10:00', close: '14:00' },
  },
  number_of_doctors: 0,
  number_of_staff: 0,
  description: '',
  status: 'pending',
  created_at: '',
  updated_at: '',
});

const originalData = ref<ClinicProfile | null>(null);

const settings = ref({
  paymentBeforeBooking: true,
  emailNotifications: true,
  smsNotifications: false,
  bookingConfirmation: true,
  autoValidation: true,
});

const stats = ref({
  totalDoctors: 0,
  totalPatients: 0,
  thisMonth: 0,
  status: 'pending',
});

// Fetch clinic data from Supabase
onMounted(async () => {
  try {
    isLoading.value = true;
    error.value = null;

    const currentUser = await roleBasedAuthService.getCurrentUser();
    if (!currentUser || currentUser.role !== 'clinic') {
      error.value = 'No authenticated clinic user found. Please sign in as a clinic.';
      return;
    }

    if (!currentUser.user || !currentUser.user.id) {
      error.value = 'Invalid user session. Please sign in again.';
      return;
    }

    console.log('Fetching clinic data for user:', currentUser.user.id);

    const clinicResult = await clinicService.getClinicByUserId(currentUser.user.id);
    if (clinicResult.success && clinicResult.clinic) {
      // Convert null values to empty strings for inputs
      const sanitizedClinic = {
        ...clinicResult.clinic,
        phone: clinicResult.clinic.phone || '',
        website: clinicResult.clinic.website || '',
        address: clinicResult.clinic.address || '',
        city: clinicResult.clinic.city || '',
        state: clinicResult.clinic.state || '',
        zip_code: clinicResult.clinic.zip_code || '',
        license_number: clinicResult.clinic.license_number || '',
        accreditation: clinicResult.clinic.accreditation || '',
        tax_id: clinicResult.clinic.tax_id || '',
        description: clinicResult.clinic.description || '',
      };

      clinicData.value = sanitizedClinic;
      originalData.value = { ...sanitizedClinic };

      // Set stats based on clinic data
      stats.value = {
        totalDoctors: clinicData.value.number_of_doctors || 0,
        totalPatients: 0, // This would come from a separate API call
        thisMonth: 0, // This would come from a separate API call
        status: clinicData.value.status || 'pending',
      };
    } else {
      error.value = clinicResult.error || 'Failed to fetch clinic data';
    }
  } catch (err) {
    console.error('Error fetching clinic data:', err);
    error.value = 'An unexpected error occurred. Please try again later.';
  } finally {
    isLoading.value = false;
  }
});

const handleEdit = () => {
  isEditing.value = true;
};

const handleCancel = () => {
  if (originalData.value) {
    clinicData.value = { ...originalData.value };
  }
  isEditing.value = false;
};

const handleSave = async () => {
  try {
    isSaving.value = true;
    error.value = null;

    if (!clinicData.value.id) {
      error.value = 'Cannot update: Missing clinic ID';
      return;
    }

    const updateResult = await clinicService.updateClinic(clinicData.value.id, clinicData.value);
    if (updateResult.success) {
      originalData.value = { ...clinicData.value };
      isEditing.value = false;
    } else {
      error.value = updateResult.error || 'Failed to update clinic information';
    }
  } catch (err) {
    console.error('Error updating clinic:', err);
    error.value = 'An unexpected error occurred while saving. Please try again.';
  } finally {
    isSaving.value = false;
  }
};

const handleSettingChange = (setting: string, value: boolean) => {
  settings.value = {
    ...settings.value,
    [setting]: value,
  };
};

const getStatusColor = (status: string) => {
  switch (status.toLowerCase()) {
    case 'active':
      return 'bg-green-100 text-green-800';
    case 'pending':
      return 'bg-yellow-100 text-yellow-800';
    case 'suspended':
      return 'bg-red-100 text-red-800';
    default:
      return 'bg-gray-100 text-gray-800';
  }
};

const getStatusText = (status: string) => {
  return status.charAt(0).toUpperCase() + status.slice(1);
};
</script>

<template>
  <div class="p-6 space-y-6">
    <!-- Header -->
    <div class="flex flex-col md:flex-row justify-between items-start md:items-center mb-6">
      <div>
        <h1 class="text-2xl font-bold text-gray-900">Clinic Settings</h1>
        <p class="text-gray-600">Manage your clinic profile and preferences</p>
      </div>
    </div>

    <!-- Loading State -->
    <div v-if="isLoading" class="flex justify-center items-center py-12">
      <Loader2 class="h-8 w-8 animate-spin text-blue-500" />
      <span class="ml-2 text-gray-600">Loading clinic information...</span>
    </div>

    <!-- Error State -->
    <div v-else-if="error" class="bg-red-50 border border-red-200 rounded-lg p-4 flex items-start">
      <AlertTriangle class="h-5 w-5 text-red-500 mt-0.5 mr-2 flex-shrink-0" />
      <div>
        <h3 class="text-sm font-medium text-red-800">Error</h3>
        <p class="text-sm text-red-700">{{ error }}</p>
      </div>
    </div>

    <div v-else class="grid grid-cols-1 lg:grid-cols-3 gap-6">
      <!-- Main Content - 2/3 width on large screens -->
      <div class="lg:col-span-2 space-y-6">
        <!-- Clinic Profile Card -->
        <Card>
          <CardHeader class="flex flex-row items-center justify-between">
            <div>
              <h2 class="text-xl font-semibold">Clinic Profile</h2>
              <p class="text-sm text-gray-500">Manage your clinic's information</p>
            </div>
            <div class="flex space-x-2">
              <Button 
                v-if="!isEditing" 
                @click="handleEdit" 
                variant="outline" 
                size="sm"
              >
                <Edit class="h-4 w-4 mr-2" />
                Edit Profile
              </Button>
              <Button 
                v-if="isEditing" 
                @click="handleCancel" 
                variant="outline" 
                size="sm"
              >
                Cancel
              </Button>
              <Button 
                v-if="isEditing" 
                @click="handleSave" 
                variant="default" 
                size="sm"
                :disabled="isSaving"
              >
                <Save v-if="!isSaving" class="h-4 w-4 mr-2" />
                <Loader2 v-else class="h-4 w-4 mr-2 animate-spin" />
                Save Changes
              </Button>
            </div>
          </CardHeader>
          <CardContent>
            <div class="space-y-6">
              <!-- Clinic Status -->
              <div class="flex items-center justify-between">
                <div>
                  <p class="text-sm font-medium text-gray-500">Clinic Status</p>
                  <div class="mt-1 flex items-center">
                    <span 
                      class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium" 
                      :class="getStatusColor(stats.status)"
                    >
                      {{ getStatusText(stats.status) }}
                    </span>
                  </div>
                </div>
                <div class="flex items-center space-x-4">
                  <div class="text-center">
                    <p class="text-2xl font-semibold">{{ stats.totalDoctors }}</p>
                    <p class="text-xs text-gray-500">Doctors</p>
                  </div>
                  <div class="text-center">
                    <p class="text-2xl font-semibold">{{ stats.totalPatients }}</p>
                    <p class="text-xs text-gray-500">Patients</p>
                  </div>
                  <div class="text-center">
                    <p class="text-2xl font-semibold">{{ stats.thisMonth }}</p>
                    <p class="text-xs text-gray-500">This Month</p>
                  </div>
                </div>
              </div>

              <!-- Basic Information -->
              <div>
                <h3 class="text-base font-medium mb-3">Basic Information</h3>
                <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label class="block text-sm font-medium text-gray-700 mb-1">Clinic Name</label>
                    <Input 
                      v-model="clinicData.clinic_name" 
                      :disabled="!isEditing" 
                      class="w-full"
                    />
                  </div>
                  <div>
                    <label class="block text-sm font-medium text-gray-700 mb-1">Email Address</label>
                    <Input 
                      v-model="clinicData.email" 
                      type="email" 
                      :disabled="!isEditing" 
                      class="w-full"
                    />
                  </div>
                  <div>
                    <label class="block text-sm font-medium text-gray-700 mb-1">Phone Number</label>
                    <Input 
                      v-model="clinicData.phone" 
                      :disabled="!isEditing" 
                      class="w-full"
                    />
                  </div>
                  <div>
                    <label class="block text-sm font-medium text-gray-700 mb-1">Website</label>
                    <Input 
                      v-model="clinicData.website" 
                      :disabled="!isEditing" 
                      class="w-full"
                    />
                  </div>
                </div>
              </div>

              <!-- Address Information -->
              <div>
                <h3 class="text-base font-medium mb-3">Address</h3>
                <div class="grid grid-cols-1 gap-4">
                  <div>
                    <label class="block text-sm font-medium text-gray-700 mb-1">Street Address</label>
                    <Input 
                      v-model="clinicData.address" 
                      :disabled="!isEditing" 
                      class="w-full"
                    />
                  </div>
                  <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
                    <div>
                      <label class="block text-sm font-medium text-gray-700 mb-1">City</label>
                      <Input 
                        v-model="clinicData.city" 
                        :disabled="!isEditing" 
                        class="w-full"
                      />
                    </div>
                    <div>
                      <label class="block text-sm font-medium text-gray-700 mb-1">State/Province</label>
                      <Input 
                        v-model="clinicData.state" 
                        :disabled="!isEditing" 
                        class="w-full"
                      />
                    </div>
                    <div>
                      <label class="block text-sm font-medium text-gray-700 mb-1">ZIP/Postal Code</label>
                      <Input 
                        v-model="clinicData.zip_code" 
                        :disabled="!isEditing" 
                        class="w-full"
                      />
                    </div>
                  </div>
                </div>
              </div>

              <!-- Legal Information -->
              <div>
                <h3 class="text-base font-medium mb-3">Legal Information</h3>
                <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label class="block text-sm font-medium text-gray-700 mb-1">License Number</label>
                    <Input 
                      v-model="clinicData.license_number" 
                      :disabled="!isEditing" 
                      class="w-full"
                    />
                  </div>
                  <div>
                    <label class="block text-sm font-medium text-gray-700 mb-1">Tax ID</label>
                    <Input 
                      v-model="clinicData.tax_id" 
                      :disabled="!isEditing" 
                      class="w-full"
                    />
                  </div>
                  <div>
                    <label class="block text-sm font-medium text-gray-700 mb-1">Accreditation</label>
                    <Input 
                      v-model="clinicData.accreditation" 
                      :disabled="!isEditing" 
                      class="w-full"
                    />
                  </div>
                  <div>
                    <label class="block text-sm font-medium text-gray-700 mb-1">Year Established</label>
                    <Input 
                      v-model="clinicData.year_established" 
                      type="number" 
                      :disabled="!isEditing" 
                      class="w-full"
                    />
                  </div>
                </div>
              </div>

              <!-- Description -->
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">Clinic Description</label>
                <textarea
                  v-model="clinicData.description"
                  :disabled="!isEditing"
                  rows="4"
                  class="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
                ></textarea>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      <!-- Sidebar - 1/3 width on large screens -->
      <div class="space-y-6">
        <!-- Settings Card -->
        <Card>
          <CardHeader>
            <h2 class="text-xl font-semibold">Preferences</h2>
            <p class="text-sm text-gray-500">Configure your clinic settings</p>
          </CardHeader>
          <CardContent>
            <div class="space-y-4">
              <!-- Payment Settings -->
              <div class="flex items-center justify-between">
                <div class="flex items-center space-x-3">
                  <div class="bg-blue-100 p-2 rounded-full">
                    <DollarSign class="h-5 w-5 text-blue-600" />
                  </div>
                  <div>
                    <p class="font-medium">Payment Before Booking</p>
                    <p class="text-sm text-gray-500">Require payment to confirm appointments</p>
                  </div>
                </div>
                <label class="relative inline-flex items-center cursor-pointer">
                  <input 
                    type="checkbox" 
                    v-model="settings.paymentBeforeBooking" 
                    class="sr-only peer"
                    @change="handleSettingChange('paymentBeforeBooking', settings.paymentBeforeBooking)"
                  />
                  <div class="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-blue-300 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-blue-600"></div>
                </label>
              </div>

              <!-- Notification Settings -->
              <div class="flex items-center justify-between">
                <div class="flex items-center space-x-3">
                  <div class="bg-blue-100 p-2 rounded-full">
                    <Bell class="h-5 w-5 text-blue-600" />
                  </div>
                  <div>
                    <p class="font-medium">Email Notifications</p>
                    <p class="text-sm text-gray-500">Receive email for new appointments</p>
                  </div>
                </div>
                <label class="relative inline-flex items-center cursor-pointer">
                  <input 
                    type="checkbox" 
                    v-model="settings.emailNotifications" 
                    class="sr-only peer"
                    @change="handleSettingChange('emailNotifications', settings.emailNotifications)"
                  />
                  <div class="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-blue-300 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-blue-600"></div>
                </label>
              </div>

              <!-- SMS Settings -->
              <div class="flex items-center justify-between">
                <div class="flex items-center space-x-3">
                  <div class="bg-blue-100 p-2 rounded-full">
                    <Bell class="h-5 w-5 text-blue-600" />
                  </div>
                  <div>
                    <p class="font-medium">SMS Notifications</p>
                    <p class="text-sm text-gray-500">Receive text messages for updates</p>
                  </div>
                </div>
                <label class="relative inline-flex items-center cursor-pointer">
                  <input 
                    type="checkbox" 
                    v-model="settings.smsNotifications" 
                    class="sr-only peer"
                    @change="handleSettingChange('smsNotifications', settings.smsNotifications)"
                  />
                  <div class="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-blue-300 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-blue-600"></div>
                </label>
              </div>

              <!-- Booking Confirmation -->
              <div class="flex items-center justify-between">
                <div class="flex items-center space-x-3">
                  <div class="bg-blue-100 p-2 rounded-full">
                    <Shield class="h-5 w-5 text-blue-600" />
                  </div>
                  <div>
                    <p class="font-medium">Booking Confirmation</p>
                    <p class="text-sm text-gray-500">Manually confirm each appointment</p>
                  </div>
                </div>
                <label class="relative inline-flex items-center cursor-pointer">
                  <input 
                    type="checkbox" 
                    v-model="settings.bookingConfirmation" 
                    class="sr-only peer"
                    @change="handleSettingChange('bookingConfirmation', settings.bookingConfirmation)"
                  />
                  <div class="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-blue-300 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-blue-600"></div>
                </label>
              </div>

              <!-- Auto Validation -->
              <div class="flex items-center justify-between">
                <div class="flex items-center space-x-3">
                  <div class="bg-blue-100 p-2 rounded-full">
                    <Clock class="h-5 w-5 text-blue-600" />
                  </div>
                  <div>
                    <p class="font-medium">Auto Validation</p>
                    <p class="text-sm text-gray-500">Automatically validate appointments</p>
                  </div>
                </div>
                <label class="relative inline-flex items-center cursor-pointer">
                  <input 
                    type="checkbox" 
                    v-model="settings.autoValidation" 
                    class="sr-only peer"
                    @change="handleSettingChange('autoValidation', settings.autoValidation)"
                  />
                  <div class="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-blue-300 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-blue-600"></div>
                </label>
              </div>
            </div>
          </CardContent>
        </Card>

        <!-- Profile Photo Card -->
        <Card>
          <CardHeader>
            <h2 class="text-xl font-semibold">Clinic Logo</h2>
            <p class="text-sm text-gray-500">Upload your clinic logo</p>
          </CardHeader>
          <CardContent>
            <div class="flex flex-col items-center justify-center space-y-4">
              <div class="h-32 w-32 rounded-full bg-gray-100 flex items-center justify-center overflow-hidden">
                <!-- Placeholder for clinic logo -->
                <Camera class="h-12 w-12 text-gray-400" />
              </div>
              <Button variant="outline" size="sm">
                <Camera class="h-4 w-4 mr-2" />
                Upload Logo
              </Button>
              <p class="text-xs text-gray-500 text-center">
                Recommended: 300x300px JPG, PNG, or GIF (max 2MB)
              </p>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  </div>
</template>
