// IgabayECare/src/modules/auth/pages/ClinicSignUpPage/ClinicSignUpPage.vue
<template>
  <ClinicSignUpForm :onSuccess="handleSuccess" />
</template>

<script setup lang="ts">
import ClinicSignUpForm from '../../../modules/auth/components/ClinicSignUpForm/ClinicSignUpForm.vue';

const handleSuccess = () => {
  // Don't redirect automatically - user needs to verify email first
  // router.push('/clinic/dashboard');
};
</script>

// IgabayECare/src/features/auth/pages/ClinicSignUpPage.tsx
import React from 'react';
import { useNavigate } from 'react-router-dom';
import { ClinicSignUpForm } from '../components/ClinicSignUpForm';

const ClinicSignUpPage: React.FC = () => {
  const navigate = useNavigate();

  const handleSuccess = () => {
    // Don't redirect automatically - user needs to verify email first
    // navigate('/clinic/dashboard');
  };

  return (
    <ClinicSignUpForm onSuccess={handleSuccess} />
  );
};

export default ClinicSignUpPage;
