// IgabayECare/src/shared/components/ui/ConfirmDialog/ConfirmDialog.vue
<template>
  <Modal
    v-model="isOpen"
    :title="title"
    size="sm"
    :closable="closable"
    @close="handleClose"
  >
    <template #header>
      <div v-if="$slots.title">
        <slot name="title" />
      </div>
      <div v-else class="flex items-center space-x-3">
        <component
          :is="variantIcon"
          :class="['h-6 w-6', variantClasses.icon]"
        />
        <h3 class="text-lg font-semibold text-gray-900">{{ title }}</h3>
      </div>
    </template>

    <!-- Content -->
    <div class="py-2">
      <slot name="content">
        <p class="text-gray-600">{{ message }}</p>
      </slot>
    </div>

    <template #footer>
      <slot name="actions">
        <div class="flex items-center justify-end space-x-3">
          <Button
            variant="outline"
            @click="handleCancel"
            :disabled="loading"
          >
            {{ cancelText }}
          </Button>
          <Button
            :variant="variantButtonType"
            :loading="loading"
            @click="handleConfirm"
          >
            {{ confirmText }}
          </Button>
        </div>
      </slot>
    </template>
  </Modal>
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { AlertTriangle, AlertCircle, Info, CheckCircle } from 'lucide-vue-next';
import { Modal } from '../Modal';
import { Button } from '../Button';
import type { ConfirmDialogProps, ConfirmDialogEmits } from './ConfirmDialog.types';
import { ComponentVariant } from '../../../core/types';

interface Props extends ConfirmDialogProps {}

const props = withDefaults(defineProps<Props>(), {
  confirmText: 'Confirm',
  cancelText: 'Cancel',
  variant: 'danger',
  loading: false,
  closable: true
});

const emit = defineEmits<ConfirmDialogEmits>();

// Internal state to handle v-model
const isOpen = ref(props.modelValue);

// Watch for prop changes
watch(() => props.modelValue, (newValue) => {
  isOpen.value = newValue;
});

// Watch for internal changes
watch(isOpen, (newValue) => {
  emit('update:modelValue', newValue);
});

// Computed properties
const variantIcon = computed(() => {
  switch (props.variant) {
    case 'danger':
      return AlertTriangle;
    case 'warning':
      return AlertTriangle;
    case 'info':
      return Info;
    case 'success':
      return CheckCircle;
    default:
      return AlertTriangle;
  }
});

const variantClasses = computed(() => {
  switch (props.variant) {
    case 'danger':
      return {
        icon: 'text-red-600',
        border: 'border-red-200'
      };
    case 'warning':
      return {
        icon: 'text-yellow-600',
        border: 'border-yellow-200'
      };
    case 'info':
      return {
        icon: 'text-blue-600',
        border: 'border-blue-200'
      };
    case 'success':
      return {
        icon: 'text-green-600',
        border: 'border-green-200'
      };
    default:
      return {
        icon: 'text-red-600',
        border: 'border-red-200'
      };
  }
});

const variantButtonType = computed(() => {
  switch (props.variant) {
    case 'danger':
      return ComponentVariant.DANGER;
    case 'warning':
      return ComponentVariant.WARNING;
    case 'info':
      return ComponentVariant.INFO;
    case 'success':
      return ComponentVariant.SUCCESS;
    default:
      return ComponentVariant.DANGER;
  }
});

// Event handlers
const handleConfirm = async () => {
  emit('confirm');
  if (!props.loading) {
    handleClose();
  }
};

const handleCancel = () => {
  emit('cancel');
  handleClose();
};

const handleClose = () => {
  isOpen.value = false;
  emit('close');
};
</script>

// IgabayECare/src/components/ui/ConfirmDialog.tsx
import React from 'react';
import { AlertTriangle, X } from 'lucide-react';
import { Button } from './Button';

interface ConfirmDialogProps {
  isOpen: boolean;
  onClose: () => void;
  onConfirm: () => void;
  title: string;
  message: string;
  confirmText?: string;
  cancelText?: string;
  variant?: 'danger' | 'warning' | 'info';
}

export const ConfirmDialog: React.FC<ConfirmDialogProps> = ({
  isOpen,
  onClose,
  onConfirm,
  title,
  message,
  confirmText = 'Confirm',
  cancelText = 'Cancel',
  variant = 'danger'
}) => {
  if (!isOpen) return null;

  const getVariantClasses = () => {
    switch (variant) {
      case 'danger':
        return {
          icon: 'text-red-600',
          button: 'bg-red-600 hover:bg-red-700 text-white',
          border: 'border-red-200'
        };
      case 'warning':
        return {
          icon: 'text-yellow-600',
          button: 'bg-yellow-600 hover:bg-yellow-700 text-white',
          border: 'border-yellow-200'
        };
      case 'info':
        return {
          icon: 'text-blue-600',
          button: 'bg-blue-600 hover:bg-blue-700 text-white',
          border: 'border-blue-200'
        };
      default:
        return {
          icon: 'text-red-600',
          button: 'bg-red-600 hover:bg-red-700 text-white',
          border: 'border-red-200'
        };
    }
  };

  const variantClasses = getVariantClasses();

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
      <div className="bg-white rounded-lg shadow-xl max-w-md w-full mx-4">
        {/* Header */}
        <div className={`flex items-center justify-between p-6 border-b ${variantClasses.border}`}>
          <div className="flex items-center space-x-3">
            <AlertTriangle className={`h-6 w-6 ${variantClasses.icon}`} />
            <h3 className="text-lg font-semibold text-gray-900">{title}</h3>
          </div>
          <button
            onClick={onClose}
            className="text-gray-400 hover:text-gray-600 transition-colors"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Content */}
        <div className="p-6">
          <p className="text-gray-600 mb-6">{message}</p>
        </div>

        {/* Actions */}
        <div className="flex items-center justify-end space-x-3 p-6 border-t border-gray-200">
          <Button
            variant="outline"
            onClick={onClose}
            className="border-gray-300 text-gray-700 hover:bg-gray-50"
          >
            {cancelText}
          </Button>
          <Button
            onClick={() => {
              onConfirm();
              onClose();
            }}
            className={variantClasses.button}
          >
            {confirmText}
          </Button>
        </div>
      </div>
    </div>
  );
};
