// IgabayECare/src/views/patient/PatientDashboard.vue
<template>
  <SkeletonDashboard v-if="loading" />
  <DashboardLayout
    v-else
    :navigationItems="navigationItems"
    :activeTab="activeTab"
    :onTabChange="setActiveTab"
    :user="user"
    :onSignOut="handleSignOut"
    :onSearch="handleSearch"
    variant="patient"
    :showNavbar="true"
  >
    <component :is="currentTabComponent" @navigate="setActiveTab" :patientId="patientId" />
  </DashboardLayout>
</template>

<script lang="ts">
import { defineComponent, ref, computed, onMounted } from 'vue';
import { useRouter } from 'vue-router';
import {
  User,
  Calendar,
  MapPin,
  History,
  Home
} from 'lucide-vue-next';
import { AuthService } from '../../modules/auth/services/AuthService';
import PatientHome from './PatientHome.vue';
import NearbyClinic from './NearbyClinic.vue';
import PatientProfileComponent from './PatientProfile.vue';
import PatientAppointments from './PatientAppointments.vue';
import PatientHistory from './PatientHistory.vue';
import { DashboardLayout } from '../../shared/components/layout/DashboardLayout/DashboardLayout.vue';
import { SkeletonDashboard } from '../../shared/components/ui/Skeleton/Skeleton.vue';

export default defineComponent({
  name: 'PatientDashboard',
  components: {
    DashboardLayout,
    SkeletonDashboard,
    PatientHome,
    NearbyClinic,
    PatientAppointments,
    PatientHistory,
    PatientProfileComponent
  },
  setup() {
    const router = useRouter();
    const user = ref<{ id?: string; name?: string; email?: string; role?: string; user?: object } | null>(null);
    const loading = ref(true);
    const activeTab = ref('home');
    const authService = new AuthService();

    const navigationItems = [
      {
        id: 'home',
        label: 'Home',
        icon: Home,
        href: '#'
      },
      {
        id: 'nearby',
        label: 'Nearby',
        icon: MapPin,
        href: '#'
      },
      {
        id: 'appointments',
        label: 'Appointments',
        icon: Calendar,
        href: '#'
      },
      {
        id: 'history',
        label: 'History',
        icon: History,
        href: '#'
      },
      {
        id: 'profile',
        label: 'Profile',
        icon: User,
        href: '#'
      }
    ];

    const patientId = computed(() => user.value?.id || user.value?.user?.id || '');

    const currentTabComponent = computed(() => {
      switch (activeTab.value) {
        case 'home':
          return PatientHome;
        case 'nearby':
          return NearbyClinic;
        case 'appointments':
          return PatientAppointments;
        case 'history':
          return PatientHistory;
        case 'profile':
          return PatientProfileComponent;
        default:
          return PatientHome;
      }
    });

    onMounted(async () => {
      try {
        const currentUser = await authService.getCurrentUser();
        if (!currentUser) {
          router.push('/signin');
          return;
        }
        user.value = currentUser;
      } catch {
        router.push('/signin');
      } finally {
        loading.value = false;
      }
    });

    const handleSignOut = async () => {
      try {
        await authService.signOut();
        router.push('/');
      } catch (error) {
        console.error('Sign out error:', error);
      }
    };

    const handleSearch = (query: string) => {
      console.log('Patient search query:', query);
    };

    const setActiveTab = (tab: string) => {
      activeTab.value = tab;
    };

    return {
      user,
      loading,
      activeTab,
      navigationItems,
      patientId,
      currentTabComponent,
      handleSignOut,
      handleSearch,
      setActiveTab
    };
  }
});
</script>

// IgabayCare/src/pages/patient/PatientDashboard.tsx
import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { 
  User, 
  Calendar, 
  MapPin, 
  History, 
  Home 
} from 'lucide-react';
import { Button } from '../../components/ui/Button';
import { authService } from '../../features/auth/utils/authService';
import PatientHome from './PatientHome';
import { NearbyClinic } from './NearbyClinic';
import { PatientProfileComponent } from './PatientProfile';
import { PatientAppointments } from './PatientAppointments';
import {PatientHistory} from './PatientHistory';
import { DashboardLayout } from '../../components/layout/DashboardLayout';
import { SkeletonDashboard } from '../../components/ui/Skeleton';

const PatientDashboard: React.FC = () => {
  const navigate = useNavigate();
  const [user, setUser] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState('home');

  useEffect(() => {
    const checkAuth = async () => {
      try {
        const currentUser = await authService.getCurrentUser();
        if (!currentUser) {
          navigate('/signin');
          return;
        }
        setUser(currentUser);
      } catch (error) {
        navigate('/signin');
      } finally {
        setLoading(false);
      }
    };

    checkAuth();
  }, [navigate]);

  const handleSignOut = async () => {
    try {
      await authService.signOut();
      navigate('/');
    } catch (error) {
      console.error('Sign out error:', error);
    }
  };

  const handleSearch = (query: string) => {
    console.log('Patient search query:', query);
  };

  const navigationItems = [
    {
      id: 'home',
      label: 'Home',
      icon: Home,
      href: '#'
    },
    {
      id: 'nearby',
      label: 'Nearby',
      icon: MapPin,
      href: '#'
    },
    {
      id: 'appointments',
      label: 'Appointments',
      icon: Calendar,
      href: '#'
    },
    {
      id: 'history',
      label: 'History',
      icon: History,
      href: '#'
    },
    {
      id: 'profile',
      label: 'Profile',
      icon: User,
      href: '#'
    }
  ];

  const patientId = user?.id || user?.user?.id || '';

  const renderContent = () => {
    switch (activeTab) {
      case 'home':
        return <PatientHome onNavigate={setActiveTab} />;
      case 'nearby':
        return <NearbyClinic />;
      case 'appointments':
        return <PatientAppointments onNavigate={setActiveTab} />;
      case 'history':
        return (
          <PatientHistory patientId={patientId} />
        );
      case 'profile':
        return <PatientProfileComponent />;
      default:
        return <PatientHome onNavigate={setActiveTab} />;
    }
  };

  if (loading) {
    return <SkeletonDashboard />;
  }

  return (
    <DashboardLayout
      navigationItems={navigationItems}
      activeTab={activeTab}
      onTabChange={setActiveTab}
      user={user}
      onSignOut={handleSignOut}
      onSearch={handleSearch}
      variant="patient"
      showNavbar={true}
    >
      {renderContent()}
    </DashboardLayout>
  );
};

export default PatientDashboard;
