// IgabayECare/src/modules/auth/views/DoctorSignInPage.vue
<template>
  <DoctorSignInForm :onSuccess="handleSuccess" />
</template>

<script setup lang="ts">
import { useRouter } from 'vue-router';
import DoctorSignInForm from '../components/DoctorSignInForm/DoctorSignInForm.vue';

const router = useRouter();

const handleSuccess = () => {
  router.push('/doctors-dashboard');
};
</script>

// IgabayCare/src/features/auth/pages/DoctorSignInPage.tsx
import React from 'react';
import { useNavigate } from 'react-router-dom';
import { DoctorSignInForm } from '../components/DoctorSignInForm';

const DoctorSignInPage: React.FC = () => {
  const navigate = useNavigate();

  const handleSuccess = () => {
    navigate('/doctor/dashboard');
  };

  return (
    <DoctorSignInForm onSuccess={handleSuccess} />
  );
};

export default DoctorSignInPage;
