// IgabayECare/src/views/clinic/ManageClinic.vue
<script setup lang="ts">
import { ref } from 'vue';
import { 
  Building, 
  Users, 
  Calendar, 
  FileText, 
  Settings, 
  BarChart3, 
  Shield, 
  CreditCard,
  Clock,
  MapPin,
  Phone,
  Mail,
  Globe,
  Award,
  FileCheck,
  UserCheck,
  AlertCircle,
  CheckCircle,
  XCircle
} from 'lucide-vue-next';
import Button from '../../components/ui/Button.vue';
import { Card, CardContent, CardHeader, CardTitle } from '../../components/ui/Card.vue';
import Modal from '../../components/ui/Modal.vue';

const activeSection = ref('overview');
const showModal = ref(false);
const modalType = ref('');

const managementSections = [
  {
    id: 'overview',
    label: 'Overview',
    icon: BarChart3,
    description: 'Clinic performance and statistics'
  },
  {
    id: 'schedule',
    label: 'Schedule Management',
    icon: Calendar,
    description: 'Operating hours and availability'
  },
  {
    id: 'services',
    label: 'Services & Specialties',
    icon: FileText,
    description: 'Medical services and specialties offered'
  },
];

const clinicStats = {
  totalPatients: 1247,
  totalDoctors: 8,
  totalStaff: 24,
  averageRating: 4.8,
  monthlyAppointments: 320,
};

const operatingHours = {
  monday: { open: '08:00', close: '18:00', closed: false },
  tuesday: { open: '08:00', close: '18:00', closed: false },
  wednesday: { open: '08:00', close: '18:00', closed: false },
  thursday: { open: '08:00', close: '18:00', closed: false },
  friday: { open: '08:00', close: '18:00', closed: false },
  saturday: { open: '09:00', close: '16:00', closed: false },
  sunday: { open: '10:00', close: '14:00', closed: false }
};

const services = [
  { id: 1, name: 'Primary Care', active: true, category: 'General' },
  { id: 2, name: 'Cardiology', active: true, category: 'Specialty' },
  { id: 3, name: 'Pediatrics', active: true, category: 'Specialty' },
  { id: 4, name: 'Dermatology', active: false, category: 'Specialty' },
  { id: 5, name: 'Laboratory Services', active: true, category: 'Diagnostic' },
  { id: 6, name: 'Radiology', active: true, category: 'Diagnostic' }
];

const licenses = [
  { id: 1, name: 'Medical License', number: 'MD-12345', expiry: '2025-12-31', status: 'valid' },
  { id: 2, name: 'Clinic Accreditation', number: 'ACC-2024-001', expiry: '2026-06-30', status: 'valid' },
  { id: 3, name: 'Insurance Provider', number: 'INS-789', expiry: '2024-08-15', status: 'expiring' }
];

const getStatusColor = (status: string) => {
  switch (status) {
    case 'active':
    case 'valid':
      return 'bg-green-100 text-green-800';
    case 'on-leave':
    case 'expiring':
      return 'bg-yellow-100 text-yellow-800';
    case 'inactive':
    case 'expired':
      return 'bg-red-100 text-red-800';
    default:
      return 'bg-gray-100 text-gray-800';
  }
};

const openModal = (type: string) => {
  modalType.value = type;
  showModal.value = true;
};

const closeModal = () => {
  showModal.value = false;
};

const formatDate = (dateString: string) => {
  const date = new Date(dateString);
  return date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric'
  });
};

const getDaysUntilExpiry = (expiryDate: string) => {
  const today = new Date();
  const expiry = new Date(expiryDate);
  const diffTime = expiry.getTime() - today.getTime();
  const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
  return diffDays;
};
</script>

<template>
  <div class="p-6 space-y-6">
    <!-- Header -->
    <div class="flex flex-col md:flex-row justify-between items-start md:items-center mb-6">
      <div>
        <h1 class="text-2xl font-bold text-gray-900">Clinic Management</h1>
        <p class="text-gray-600">Manage your clinic operations and settings</p>
      </div>
    </div>

    <!-- Management Sections -->
    <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
      <Card 
        v-for="section in managementSections" 
        :key="section.id"
        class="cursor-pointer transition-all hover:shadow-md"
        :class="activeSection === section.id ? 'ring-2 ring-blue-500' : ''"
        @click="activeSection = section.id"
      >
        <CardContent class="p-6 flex items-start space-x-4">
          <div class="bg-blue-100 p-3 rounded-full">
            <component :is="section.icon" class="h-6 w-6 text-blue-600" />
          </div>
          <div>
            <h3 class="font-semibold text-lg">{{ section.label }}</h3>
            <p class="text-gray-500 text-sm">{{ section.description }}</p>
          </div>
        </CardContent>
      </Card>
    </div>

    <!-- Overview Section -->
    <div v-if="activeSection === 'overview'" class="space-y-6">
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-4">
        <Card>
          <CardContent class="p-6">
            <div class="flex flex-col items-center">
              <Users class="h-8 w-8 text-blue-500 mb-2" />
              <p class="text-3xl font-bold">{{ clinicStats.totalPatients }}</p>
              <p class="text-sm text-gray-500">Total Patients</p>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent class="p-6">
            <div class="flex flex-col items-center">
              <UserCheck class="h-8 w-8 text-green-500 mb-2" />
              <p class="text-3xl font-bold">{{ clinicStats.totalDoctors }}</p>
              <p class="text-sm text-gray-500">Doctors</p>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent class="p-6">
            <div class="flex flex-col items-center">
              <Users class="h-8 w-8 text-purple-500 mb-2" />
              <p class="text-3xl font-bold">{{ clinicStats.totalStaff }}</p>
              <p class="text-sm text-gray-500">Staff Members</p>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent class="p-6">
            <div class="flex flex-col items-center">
              <Calendar class="h-8 w-8 text-orange-500 mb-2" />
              <p class="text-3xl font-bold">{{ clinicStats.monthlyAppointments }}</p>
              <p class="text-sm text-gray-500">Monthly Appointments</p>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent class="p-6">
            <div class="flex flex-col items-center">
              <Award class="h-8 w-8 text-yellow-500 mb-2" />
              <p class="text-3xl font-bold">{{ clinicStats.averageRating }}</p>
              <p class="text-sm text-gray-500">Average Rating</p>
            </div>
          </CardContent>
        </Card>
      </div>

      <!-- Licenses and Certifications -->
      <Card>
        <CardHeader>
          <CardTitle class="flex items-center">
            <Shield class="h-5 w-5 mr-2 text-blue-500" />
            Licenses & Certifications
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div class="overflow-x-auto">
            <table class="w-full text-sm text-left">
              <thead class="text-xs text-gray-700 uppercase bg-gray-50">
                <tr>
                  <th class="px-6 py-3">License</th>
                  <th class="px-6 py-3">Number</th>
                  <th class="px-6 py-3">Expiry Date</th>
                  <th class="px-6 py-3">Status</th>
                  <th class="px-6 py-3">Actions</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="license in licenses" :key="license.id" class="bg-white border-b">
                  <td class="px-6 py-4 font-medium text-gray-900">{{ license.name }}</td>
                  <td class="px-6 py-4">{{ license.number }}</td>
                  <td class="px-6 py-4">{{ formatDate(license.expiry) }}</td>
                  <td class="px-6 py-4">
                    <span 
                      class="px-2 py-1 text-xs rounded-full" 
                      :class="getStatusColor(license.status)"
                    >
                      {{ license.status.charAt(0).toUpperCase() + license.status.slice(1) }}
                      <span v-if="license.status === 'expiring'">
                        ({{ getDaysUntilExpiry(license.expiry) }} days)
                      </span>
                    </span>
                  </td>
                  <td class="px-6 py-4">
                    <Button variant="outline" size="sm" @click="openModal('license')">Update</Button>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </CardContent>
      </Card>
    </div>

    <!-- Schedule Management Section -->
    <div v-if="activeSection === 'schedule'" class="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle class="flex items-center">
            <Clock class="h-5 w-5 mr-2 text-blue-500" />
            Operating Hours
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div class="space-y-4">
            <div v-for="(hours, day) in operatingHours" :key="day" class="flex items-center justify-between py-2 border-b border-gray-100">
              <div class="font-medium capitalize">{{ day }}</div>
              <div class="flex items-center space-x-4">
                <div v-if="!hours.closed" class="flex items-center space-x-2">
                  <div class="text-sm text-gray-600">
                    {{ hours.open }} - {{ hours.close }}
                  </div>
                </div>
                <div v-else class="text-sm text-gray-600">
                  Closed
                </div>
                <Button variant="outline" size="sm" @click="openModal('hours')">Edit</Button>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>

    <!-- Services Section -->
    <div v-if="activeSection === 'services'" class="space-y-6">
      <Card>
        <CardHeader class="flex flex-row items-center justify-between">
          <CardTitle class="flex items-center">
            <FileCheck class="h-5 w-5 mr-2 text-blue-500" />
            Services & Specialties
          </CardTitle>
          <Button variant="default" size="sm" @click="openModal('service')">
            Add Service
          </Button>
        </CardHeader>
        <CardContent>
          <div class="overflow-x-auto">
            <table class="w-full text-sm text-left">
              <thead class="text-xs text-gray-700 uppercase bg-gray-50">
                <tr>
                  <th class="px-6 py-3">Service Name</th>
                  <th class="px-6 py-3">Category</th>
                  <th class="px-6 py-3">Status</th>
                  <th class="px-6 py-3">Actions</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="service in services" :key="service.id" class="bg-white border-b">
                  <td class="px-6 py-4 font-medium text-gray-900">{{ service.name }}</td>
                  <td class="px-6 py-4">{{ service.category }}</td>
                  <td class="px-6 py-4">
                    <span 
                      class="px-2 py-1 text-xs rounded-full" 
                      :class="getStatusColor(service.active ? 'active' : 'inactive')"
                    >
                      {{ service.active ? 'Active' : 'Inactive' }}
                    </span>
                  </td>
                  <td class="px-6 py-4 flex space-x-2">
                    <Button variant="outline" size="sm" @click="openModal('editService')">Edit</Button>
                    <Button 
                      variant="outline" 
                      size="sm"
                      :class="service.active ? 'text-red-600 border-red-200 hover:bg-red-50' : 'text-green-600 border-green-200 hover:bg-green-50'"
                    >
                      {{ service.active ? 'Deactivate' : 'Activate' }}
                    </Button>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </CardContent>
      </Card>
    </div>

    <!-- Modals -->
    <Modal v-if="showModal" @close="closeModal" :title="modalType === 'license' ? 'Update License' : modalType === 'hours' ? 'Edit Operating Hours' : modalType === 'service' ? 'Add Service' : 'Edit Service'">
      <div class="p-6">
        <!-- License Modal Content -->
        <div v-if="modalType === 'license'" class="space-y-4">
          <p>Update license information form would go here</p>
          <div class="flex justify-end space-x-2">
            <Button variant="outline" @click="closeModal">Cancel</Button>
            <Button variant="default">Save Changes</Button>
          </div>
        </div>

        <!-- Hours Modal Content -->
        <div v-if="modalType === 'hours'" class="space-y-4">
          <p>Edit operating hours form would go here</p>
          <div class="flex justify-end space-x-2">
            <Button variant="outline" @click="closeModal">Cancel</Button>
            <Button variant="default">Save Changes</Button>
          </div>
        </div>

        <!-- Service Modal Content -->
        <div v-if="modalType === 'service' || modalType === 'editService'" class="space-y-4">
          <p>{{ modalType === 'service' ? 'Add' : 'Edit' }} service form would go here</p>
          <div class="flex justify-end space-x-2">
            <Button variant="outline" @click="closeModal">Cancel</Button>
            <Button variant="default">{{ modalType === 'service' ? 'Add Service' : 'Save Changes' }}</Button>
          </div>
        </div>
      </div>
    </Modal>
  </div>
</template>

// IgabayCare/src/pages/clinic/ManageClinic.tsx
import React, { useState } from 'react';
import { 
  Building, 
  Users, 
  Calendar, 
  FileText, 
  Settings, 
  BarChart3, 
  Shield, 
  CreditCard,
  Clock,
  MapPin,
  Phone,
  Mail,
  Globe,
  Award,
  FileCheck,
  UserCheck,
  AlertCircle,
  CheckCircle,
  XCircle
} from 'lucide-react';
import { Button } from '../../components/ui/Button';
import { Card, CardContent, CardHeader, CardTitle } from '../../components/ui/Card';
import { Modal } from '../../components/ui/Modal';

export const ManageClinic: React.FC = () => {
  const [activeSection, setActiveSection] = useState('overview');
  const [showModal, setShowModal] = useState(false);
  const [modalType, setModalType] = useState('');

  const managementSections = [
    {
      id: 'overview',
      label: 'Overview',
      icon: BarChart3,
      description: 'Clinic performance and statistics'
    },
  
    {
      id: 'schedule',
      label: 'Schedule Management',
      icon: Calendar,
      description: 'Operating hours and availability'
    },
    {
      id: 'services',
      label: 'Services & Specialties',
      icon: FileText,
      description: 'Medical services and specialties offered'
    },

 
  ];

  const clinicStats = {
    totalPatients: 1247,
    totalDoctors: 8,
    totalStaff: 24,
    averageRating: 4.8,
    monthlyAppointments: 320,
  };

  

  const operatingHours = {
    monday: { open: '08:00', close: '18:00', closed: false },
    tuesday: { open: '08:00', close: '18:00', closed: false },
    wednesday: { open: '08:00', close: '18:00', closed: false },
    thursday: { open: '08:00', close: '18:00', closed: false },
    friday: { open: '08:00', close: '18:00', closed: false },
    saturday: { open: '09:00', close: '16:00', closed: false },
    sunday: { open: '10:00', close: '14:00', closed: false }
  };

  const services = [
    { id: 1, name: 'Primary Care', active: true, category: 'General' },
    { id: 2, name: 'Cardiology', active: true, category: 'Specialty' },
    { id: 3, name: 'Pediatrics', active: true, category: 'Specialty' },
    { id: 4, name: 'Dermatology', active: false, category: 'Specialty' },
    { id: 5, name: 'Laboratory Services', active: true, category: 'Diagnostic' },
    { id: 6, name: 'Radiology', active: true, category: 'Diagnostic' }
  ];

  const licenses = [
    { id: 1, name: 'Medical License', number: 'MD-12345', expiry: '2025-12-31', status: 'valid' },
    { id: 2, name: 'Clinic Accreditation', number: 'ACC-2024-001', expiry: '2026-06-30', status: 'valid' },
    { id: 3, name: 'Insurance Provider', number: 'INS-789', expiry: '2024-08-15', status: 'expiring' }
  ];

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'active':
      case 'valid':
        return 'bg-green-100 text-green-800';
      case 'on-leave':
      case 'expiring':
        return 'bg-yellow-100 text-yellow-800';
      case 'inactive':
      case 'expired':
        return 'bg-red-100 text-red-800';
      default:
        return 'bg-gray-100 text-gray-800';
    }
  };

  const getStatusIcon = (status: string) => {
    switch (status) {
      case 'active':
      case 'valid':
        return <CheckCircle size={16} className="text-green-600" />;
      case 'on-leave':
      case 'expiring':
        return <AlertCircle size={16} className="text-yellow-600" />;
      case 'inactive':
      case 'expired':
        return <XCircle size={16} className="text-red-600" />;
      default:
        return null;
    }
  };

  const renderOverview = () => (
    <div className="space-y-6">
      {/* Stats Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        <Card>
          <CardContent className="p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-gray-600">Total Patients</p>
                <p className="text-3xl font-bold text-gray-900">{clinicStats.totalPatients}</p>
              </div>
              <Users className="h-8 w-8 text-blue-600" />
            </div>
          </CardContent>
        </Card>

     

        <Card>
          <CardContent className="p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-gray-600">Monthly Appointments</p>
                <p className="text-3xl font-bold text-gray-900">{clinicStats.monthlyAppointments}</p>
              </div>
              <Calendar className="h-8 w-8 text-purple-600" />
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-gray-600">Average Rating</p>
                <p className="text-3xl font-bold text-gray-900">{clinicStats.averageRating}</p>
              </div>
              <Award className="h-8 w-8 text-yellow-600" />
            </div>
          </CardContent>
        </Card>

        

        <Card>
          <CardContent className="p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-gray-600">Total Staff</p>
                <p className="text-3xl font-bold text-gray-900">{clinicStats.totalStaff}</p>
              </div>
              <Users className="h-8 w-8 text-orange-600" />
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Quick Actions */}
      <Card>
        <CardHeader>
          <CardTitle>Quick Actions</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
            <Button variant="outline" onClick={() => { setModalType('add-staff'); setShowModal(true); }}>
              <Users className="h-4 w-4 mr-2" />
              Add Staff
            </Button>
            <Button variant="outline" onClick={() => { setModalType('update-hours'); setShowModal(true); }}>
              <Clock className="h-4 w-4 mr-2" />
              Update Hours
            </Button>
            <Button variant="outline" onClick={() => { setModalType('add-service'); setShowModal(true); }}>
              <FileText className="h-4 w-4 mr-2" />
              Add Service
            </Button>
            <Button variant="outline" onClick={() => { setModalType('upload-license'); setShowModal(true); }}>
              <FileCheck className="h-4 w-4 mr-2" />
              Upload License
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  );

  

  const renderSchedule = () => (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <h3 className="text-lg font-semibold text-gray-900">Operating Hours</h3>
        <Button onClick={() => { setModalType('update-hours'); setShowModal(true); }}>
          <Clock className="h-4 w-4 mr-2" />
          Update Hours
        </Button>
      </div>

      <Card>
        <CardContent className="p-6">
          <div className="grid gap-4">
            {Object.entries(operatingHours).map(([day, hours]) => (
              <div key={day} className="flex items-center justify-between py-2 border-b border-gray-100 last:border-b-0">
                <div className="flex items-center space-x-3">
                  <span className="w-20 font-medium text-gray-900 capitalize">{day}</span>
                  {hours.closed ? (
                    <span className="text-red-600 font-medium">Closed</span>
                  ) : (
                    <span className="text-gray-600">
                      {hours.open} - {hours.close}
                    </span>
                  )}
                </div>
                <Button variant="outline" size="sm">
                  Edit
                </Button>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>
    </div>
  );

  const renderServices = () => (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <h3 className="text-lg font-semibold text-gray-900">Services & Specialties</h3>
        <Button onClick={() => { setModalType('add-service'); setShowModal(true); }}>
          <FileText className="h-4 w-4 mr-2" />
          Add Service
        </Button>
      </div>

      <div className="grid gap-4">
        {services.map((service) => (
          <Card key={service.id}>
            <CardContent className="p-6">
              <div className="flex items-center justify-between">
                <div>
                  <h4 className="font-semibold text-gray-900">{service.name}</h4>
                  <p className="text-sm text-gray-600">{service.category}</p>
                </div>
                <div className="flex items-center space-x-2">
                  <span className={`px-3 py-1 text-sm font-medium rounded-full ${getStatusColor(service.active ? 'active' : 'inactive')}`}>
                    {service.active ? 'Active' : 'Inactive'}
                  </span>
                  <Button variant="outline" size="sm">
                    Edit
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );

 


  const renderContent = () => {
    switch (activeSection) {
      case 'overview':
        return renderOverview();
    
      case 'schedule':
        return renderSchedule();
      case 'services':
        return renderServices();
      
      default:
        return renderOverview();
    }
  };

  return (
    <div className="p-6">
      <div className="mb-6">
        <h1 className="text-3xl font-bold text-gray-900 mb-2">Manage Clinic</h1>
        <p className="text-gray-600">Comprehensive clinic management and administration</p>
      </div>

      {/* Management Navigation */}
      <div className="mb-8">
        <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4">
          {managementSections.map((section) => {
            const Icon = section.icon;
            return (
              <button
                key={section.id}
                onClick={() => setActiveSection(section.id)}
                className={`p-4 rounded-lg border-2 transition-all ${
                  activeSection === section.id
                    ? 'border-blue-500 bg-blue-50 text-blue-700'
                    : 'border-gray-200 bg-white text-gray-700 hover:border-gray-300 hover:bg-gray-50'
                }`}
              >
                <div className="text-center">
                  <Icon className="h-8 w-8 mx-auto mb-2" />
                  <h3 className="font-semibold text-sm">{section.label}</h3>
                  <p className="text-xs text-gray-500 mt-1">{section.description}</p>
                </div>
              </button>
            );
          })}
        </div>
      </div>

      {/* Content Area */}
      <div className="bg-white rounded-lg">
        {renderContent()}
      </div>

      {/* Modal for various actions */}
      <Modal
        isOpen={showModal}
        onClose={() => setShowModal(false)}
        title={`${modalType.split('-').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(' ')}`}
        size="md"
      >
        <div className="p-6">
          <p className="text-gray-600 mb-4">
            {modalType === 'add-staff' && 'Add a new staff member to your clinic.'}
            {modalType === 'update-hours' && 'Update your clinic operating hours.'}
            {modalType === 'add-service' && 'Add a new medical service or specialty.'}
            {modalType === 'upload-license' && 'Upload a new license or certification.'}
            {modalType === 'add-insurance' && 'Add a new insurance provider.'}
          </p>
          <div className="flex justify-end space-x-3">
            <Button variant="outline" onClick={() => setShowModal(false)}>
              Cancel
            </Button>
            <Button>
              Save
            </Button>
          </div>
        </div>
      </Modal>
    </div>
  );
};
