// IgabayCare/src/features/auth/pages/ClinicSignUpPage.tsx
import React from 'react';
import { useNavigate } from 'react-router-dom';
import { ClinicSignUpForm } from '../components/ClinicSignUpForm';

const ClinicSignUpPage: React.FC = () => {
  const navigate = useNavigate();

  const handleSuccess = () => {
    // Redirect to clinic dashboard after successful registration
    navigate('/clinic/dashboard');
  };

  return (
    <ClinicSignUpForm onSuccess={handleSuccess} />
  );
};

export default ClinicSignUpPage;

// IgabayECare/src/modules/auth/views/ClinicSignUpPage.vue
<template>
  <ClinicSignUpForm :onSuccess="handleSuccess" />
</template>

<script setup lang="ts">
import { useRouter } from 'vue-router';
import ClinicSignUpForm from '../components/ClinicSignUpForm/ClinicSignUpForm.vue';

const router = useRouter();

const handleSuccess = () => {
  router.push('/clinic-signin');
};
</script>
