// IgabayCare/src/components/ui/Card.tsx
import React from 'react';

interface CardProps {
  children: React.ReactNode;
  className?: string;
  hover?: boolean;
}

export const Card: React.FC<CardProps> = ({ children, className = '', hover = false }) => {
  return (
    <div className={`
      bg-white rounded-xl shadow-sm border border-gray-200 
      ${hover ? 'hover:shadow-md hover:border-theme-light transition-all duration-200' : ''}
      ${className}
    `}>
      {children}
    </div>
  );
};

export const CardHeader: React.FC<{ children: React.ReactNode; className?: string }> = ({ 
  children, 
  className = '' 
}) => {
  return (
    <div className={`px-6 py-4 border-b border-gray-200 ${className}`}>
      {children}
    </div>
  );
};

export const CardContent: React.FC<{ children: React.ReactNode; className?: string }> = ({ 
  children, 
  className = '' 
}) => {
  return (
    <div className={`px-6 py-4 ${className}`}>
      {children}
    </div>
  );
};

export const CardFooter: React.FC<{ children: React.ReactNode; className?: string }> = ({ 
  children, 
  className = '' 
}) => {
  return (
    <div className={`px-6 py-4 border-t border-gray-200 ${className}`}>
      {children}
    </div>
  );
};

export const CardTitle: React.FC<{ children: React.ReactNode; className?: string }> = ({ 
  children, 
  className = '' 
}) => {
  return (
    <h3 className={`text-lg font-semibold text-gray-900 ${className}`}>
      {children}
    </h3>
  );
};

export const CardDescription: React.FC<{ children: React.ReactNode; className?: string }> = ({ 
  children, 
  className = '' 
}) => {
  return (
    <p className={`text-sm text-gray-600 ${className}`}>
      {children}
    </p>
  );
};

// IgabayECare/src/shared/components/ui/Card/Card.vue
<template>
  <div :class="cardClasses">
    <slot />
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import type { CardProps } from './Card.types';

interface Props extends CardProps {}

const props = withDefaults(defineProps<Props>(), {
  hover: false,
  shadow: 'sm',
  border: true,
  padding: 'md'
});

const cardClasses = computed(() => {
  const baseClasses = ['bg-white', 'rounded-xl'];

  // Shadow classes
  const shadowClasses = {
    none: [],
    sm: ['shadow-sm'],
    md: ['shadow-md'],
    lg: ['shadow-lg'],
    xl: ['shadow-xl']
  };

  // Border classes
  const borderClasses = props.border ? ['border', 'border-gray-200'] : [];

  // Hover classes
  const hoverClasses = props.hover
    ? ['hover:shadow-md', 'hover:border-theme-light', 'transition-all', 'duration-200']
    : [];

  // Padding classes (applied to the card itself if no slots)
  const paddingClasses = {
    none: [],
    sm: ['p-3'],
    md: ['p-6'],
    lg: ['p-8']
  };

  return [
    ...baseClasses,
    ...shadowClasses[props.shadow],
    ...borderClasses,
    ...hoverClasses
  ];
});
</script>
