// IgabayECare/src/views/clinic/ClinicPatients.vue
<script setup lang="ts">
import { ref } from 'vue';
import { User, Search, Filter, MoreHorizontal, Phone, Mail, Calendar, FileText, Eye } from 'lucide-vue-next';
import Button from '../../components/ui/Button.vue';
import { Card, CardContent, CardHeader, CardTitle } from '../../components/ui/Card.vue';
import Input from '../../components/ui/Input.vue';
import Modal from '../../components/ui/Modal.vue';

const searchQuery = ref('');
const selectedFilter = ref('all');
const showPatientModal = ref(false);
const selectedPatient = ref<any>(null);

const patients = [
  {
    id: 1,
    name: 'John Smith',
    age: 35,
    gender: 'Male',
    email: 'john.smith@email.com',
    phone: '+1 234-567-8900',
    lastVisit: '2024-01-15',
    nextAppointment: '2024-02-20',
    status: 'active',
    primaryDoctor: 'Dr. Sarah Johnson',
    medicalHistory: ['Hypertension', 'Diabetes Type 2'],
    allergies: ['Penicillin'],
    emergencyContact: 'Jane Smith (+1 234-567-8901)'
  },
  {
    id: 2,
    name: 'Emily Davis',
    age: 28,
    gender: 'Female',
    email: 'emily.davis@email.com',
    phone: '+1 234-567-8901',
    lastVisit: '2024-01-10',
    nextAppointment: null,
    status: 'active',
    primaryDoctor: 'Dr. Emily Davis',
    medicalHistory: ['Asthma'],
    allergies: ['Dust', 'Pollen'],
    emergencyContact: 'Mike Davis (+1 234-567-8902)'
  },
  {
    id: 3,
    name: 'Michael Chen',
    age: 42,
    gender: 'Male',
    email: 'michael.chen@email.com',
    phone: '+1 234-567-8902',
    lastVisit: '2024-01-05',
    nextAppointment: '2024-01-25',
    status: 'active',
    primaryDoctor: 'Dr. Michael Wilson',
    medicalHistory: ['Heart Disease', 'High Cholesterol'],
    allergies: ['Shellfish'],
    emergencyContact: 'Lisa Chen (+1 234-567-8903)'
  },
  {
    id: 4,
    name: 'Sarah Brown',
    age: 31,
    gender: 'Female',
    email: 'sarah.brown@email.com',
    phone: '+1 234-567-8903',
    lastVisit: '2024-01-12',
    nextAppointment: null,
    status: 'inactive',
    primaryDoctor: 'Dr. Sarah Johnson',
    medicalHistory: ['Migraine'],
    allergies: ['None'],
    emergencyContact: 'Tom Brown (+1 234-567-8904)'
  }
];

const filters = [
  { id: 'all', label: 'All Patients' },
  { id: 'active', label: 'Active' },
  { id: 'inactive', label: 'Inactive' },
  { id: 'has-appointment', label: 'Has Appointment' },
  { id: 'no-appointment', label: 'No Appointment' }
];

const filteredPatients = computed(() => {
  return patients.filter(patient => {
    const matchesSearch = patient.name.toLowerCase().includes(searchQuery.value.toLowerCase()) ||
                       patient.email.toLowerCase().includes(searchQuery.value.toLowerCase());
    const matchesFilter = selectedFilter.value === 'all' || 
                       patient.status === selectedFilter.value ||
                       (selectedFilter.value === 'has-appointment' && patient.nextAppointment) ||
                       (selectedFilter.value === 'no-appointment' && !patient.nextAppointment);
    return matchesSearch && matchesFilter;
  });
});

const handleViewPatient = (patient: any) => {
  selectedPatient.value = patient;
  showPatientModal.value = true;
};

const getStatusColor = (status: string) => {
  switch (status) {
    case 'active':
      return 'bg-green-100 text-green-800';
    case 'inactive':
      return 'bg-gray-100 text-gray-800';
    default:
      return 'bg-blue-100 text-blue-800';
  }
};

const formatDate = (dateString: string | null) => {
  if (!dateString) return 'Not scheduled';
  const date = new Date(dateString);
  return date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric'
  });
};
</script>

<template>
  <div class="p-6 space-y-6">
    <!-- Header -->
    <div class="flex flex-col md:flex-row justify-between items-start md:items-center mb-6">
      <div>
        <h1 class="text-2xl font-bold text-gray-900">Registered Patients</h1>
        <p class="text-gray-600">View and manage patient records</p>
      </div>
    </div>

    <!-- Filters -->
    <div class="flex flex-col md:flex-row gap-4">
      <div class="relative flex-grow">
        <Search class="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 h-4 w-4" />
        <Input
          v-model="searchQuery"
          placeholder="Search patients by name or email"
          class="pl-10"
        />
      </div>
      <div class="w-full md:w-64">
        <select
          v-model="selectedFilter"
          class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
        >
          <option v-for="filter in filters" :key="filter.id" :value="filter.id">
            {{ filter.label }}
          </option>
        </select>
      </div>
    </div>

    <!-- Patients Grid -->
    <div v-if="filteredPatients.length === 0" class="text-center py-12">
      <User class="h-12 w-12 mx-auto text-gray-400" />
      <h3 class="mt-4 text-lg font-medium text-gray-900">No patients found</h3>
      <p class="mt-2 text-gray-500">
        Try adjusting your filters or search criteria
      </p>
    </div>

    <div v-else class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
      <Card v-for="patient in filteredPatients" :key="patient.id" class="overflow-hidden border-0 shadow-sm hover:shadow-md transition-shadow">
        <CardHeader class="pb-0 pt-6 px-6">
          <div class="flex justify-between items-start">
            <div class="flex items-center space-x-4">
              <div class="h-12 w-12 rounded-full bg-blue-100 flex items-center justify-center text-blue-600">
                <User class="h-6 w-6" />
              </div>
              <div>
                <CardTitle class="text-lg font-semibold">
                  {{ patient.name }}
                </CardTitle>
                <div class="flex items-center mt-1">
                  <span class="text-sm text-gray-500 mr-2">{{ patient.age }} yrs, {{ patient.gender }}</span>
                  <span class="px-2 py-0.5 text-xs rounded-full" :class="getStatusColor(patient.status)">
                    {{ patient.status.charAt(0).toUpperCase() + patient.status.slice(1) }}
                  </span>
                </div>
              </div>
            </div>
            <Button variant="ghost" size="sm" class="h-8 w-8 p-0">
              <MoreHorizontal class="h-4 w-4" />
            </Button>
          </div>
        </CardHeader>
        <CardContent class="p-6">
          <div class="space-y-3">
            <div class="flex items-center text-sm">
              <Mail class="h-4 w-4 mr-2 text-gray-500" />
              <span>{{ patient.email }}</span>
            </div>
            <div class="flex items-center text-sm">
              <Phone class="h-4 w-4 mr-2 text-gray-500" />
              <span>{{ patient.phone }}</span>
            </div>
            <div class="flex items-center text-sm">
              <Calendar class="h-4 w-4 mr-2 text-gray-500" />
              <span>Next Appointment: {{ formatDate(patient.nextAppointment) }}</span>
            </div>
            <div class="flex items-center text-sm">
              <User class="h-4 w-4 mr-2 text-gray-500" />
              <span>{{ patient.primaryDoctor }}</span>
            </div>
          </div>
          <div class="mt-4 pt-4 border-t border-gray-100 flex justify-end">
            <Button
              @click="handleViewPatient(patient)"
              variant="outline"
              size="sm"
              class="text-blue-600 border-blue-200 hover:bg-blue-50"
            >
              <Eye class="h-4 w-4 mr-2" />
              View Details
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>

    <!-- Patient Details Modal -->
    <Modal v-if="showPatientModal" @close="showPatientModal = false" title="Patient Details">
      <div class="p-6">
        <div v-if="selectedPatient" class="space-y-6">
          <!-- Basic Info -->
          <div>
            <h3 class="text-lg font-medium text-gray-900 mb-3">Basic Information</h3>
            <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <p class="text-sm font-medium text-gray-500">Full Name</p>
                <p class="text-base">{{ selectedPatient.name }}</p>
              </div>
              <div>
                <p class="text-sm font-medium text-gray-500">Age & Gender</p>
                <p class="text-base">{{ selectedPatient.age }} years, {{ selectedPatient.gender }}</p>
              </div>
              <div>
                <p class="text-sm font-medium text-gray-500">Email</p>
                <p class="text-base">{{ selectedPatient.email }}</p>
              </div>
              <div>
                <p class="text-sm font-medium text-gray-500">Phone</p>
                <p class="text-base">{{ selectedPatient.phone }}</p>
              </div>
              <div>
                <p class="text-sm font-medium text-gray-500">Status</p>
                <p class="inline-flex px-2 py-1 text-sm rounded-full" :class="getStatusColor(selectedPatient.status)">
                  {{ selectedPatient.status.charAt(0).toUpperCase() + selectedPatient.status.slice(1) }}
                </p>
              </div>
              <div>
                <p class="text-sm font-medium text-gray-500">Primary Doctor</p>
                <p class="text-base">{{ selectedPatient.primaryDoctor }}</p>
              </div>
            </div>
          </div>

          <!-- Appointments -->
          <div>
            <h3 class="text-lg font-medium text-gray-900 mb-3">Appointments</h3>
            <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <p class="text-sm font-medium text-gray-500">Last Visit</p>
                <p class="text-base">{{ formatDate(selectedPatient.lastVisit) }}</p>
              </div>
              <div>
                <p class="text-sm font-medium text-gray-500">Next Appointment</p>
                <p class="text-base">{{ formatDate(selectedPatient.nextAppointment) }}</p>
              </div>
            </div>
          </div>

          <!-- Medical Information -->
          <div>
            <h3 class="text-lg font-medium text-gray-900 mb-3">Medical Information</h3>
            <div class="space-y-4">
              <div>
                <p class="text-sm font-medium text-gray-500 mb-1">Medical History</p>
                <div class="flex flex-wrap gap-2">
                  <span
                    v-for="(condition, index) in selectedPatient.medicalHistory"
                    :key="index"
                    class="px-2 py-1 bg-blue-50 text-blue-700 rounded-full text-sm"
                  >
                    {{ condition }}
                  </span>
                  <span v-if="selectedPatient.medicalHistory.length === 0" class="text-gray-500">
                    No medical history recorded
                  </span>
                </div>
              </div>
              <div>
                <p class="text-sm font-medium text-gray-500 mb-1">Allergies</p>
                <div class="flex flex-wrap gap-2">
                  <span
                    v-for="(allergy, index) in selectedPatient.allergies"
                    :key="index"
                    class="px-2 py-1 bg-red-50 text-red-700 rounded-full text-sm"
                  >
                    {{ allergy }}
                  </span>
                  <span v-if="selectedPatient.allergies.length === 0 || selectedPatient.allergies[0] === 'None'" class="text-gray-500">
                    No allergies recorded
                  </span>
                </div>
              </div>
              <div>
                <p class="text-sm font-medium text-gray-500 mb-1">Emergency Contact</p>
                <p class="text-base">{{ selectedPatient.emergencyContact }}</p>
              </div>
            </div>
          </div>

          <div class="flex justify-end space-x-3 pt-4 border-t border-gray-200">
            <Button
              @click="showPatientModal = false"
              variant="outline"
              class="border-gray-300 text-gray-700"
            >
              Close
            </Button>
            <Button variant="default">
              <FileText class="h-4 w-4 mr-2" />
              View Full Records
            </Button>
          </div>
        </div>
      </div>
    </Modal>
  </div>
</template>

// IgabayCare/src/components/clinic/ClinicPatients.tsx
import React, { useState } from 'react';
import { Search, User, Phone, Mail, Calendar, FileText, Eye } from 'lucide-react';
import { Button } from '../ui/Button';
import { Input } from '../ui/Input';
import { Card, CardContent } from '../ui/Card';
import { Modal } from '../ui/Modal';

export const ClinicPatients: React.FC = () => {
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedPatient, setSelectedPatient] = useState<any>(null);
  const [showDetailsModal, setShowDetailsModal] = useState(false);

  const mockPatients = [
    {
      id: 1,
      name: 'John Smith',
      email: 'john.smith@email.com',
      phone: '+1 234-567-8900',
      dateOfBirth: '1988-05-15',
      address: '123 Main Street, Downtown, City 12345',
      bloodType: 'O+',
      allergies: ['Penicillin'],
      lastVisit: '2023-12-20',
      totalVisits: 8,
      upcomingAppointments: 1,
      medicalHistory: [
        {
          date: '2023-12-20',
          diagnosis: 'Annual Checkup',
          doctor: 'Dr. Sarah Johnson',
          notes: 'Patient in good health, all vitals normal'
        },
        {
          date: '2023-08-15',
          diagnosis: 'Flu symptoms',
          doctor: 'Dr. Emily Davis',
          notes: 'Prescribed medication, rest recommended'
        }
      ]
    },
    {
      id: 2,
      name: 'Emily Davis',
      email: 'emily.davis@email.com',
      phone: '+1 234-567-8901',
      dateOfBirth: '1995-03-22',
      address: '456 Oak Avenue, Suburbs, City 12346',
      bloodType: 'A+',
      allergies: [],
      lastVisit: '2024-01-10',
      totalVisits: 5,
      upcomingAppointments: 0,
      medicalHistory: [
        {
          date: '2024-01-10',
          diagnosis: 'Follow-up consultation',
          doctor: 'Dr. Sarah Johnson',
          notes: 'Treatment responding well, continue medication'
        }
      ]
    },
    {
      id: 3,
      name: 'Michael Chen',
      email: 'michael.chen@email.com',
      phone: '+1 234-567-8902',
      dateOfBirth: '1982-11-08',
      address: '789 Pine Street, Eastside, City 12347',
      bloodType: 'B+',
      allergies: ['Shellfish', 'Dust'],
      lastVisit: '2023-11-25',
      totalVisits: 12,
      upcomingAppointments: 2,
      medicalHistory: [
        {
          date: '2023-11-25',
          diagnosis: 'Hypertension Management',
          doctor: 'Dr. Michael Wilson',
          notes: 'Blood pressure controlled, continue current medication'
        }
      ]
    },
    {
      id: 4,
      name: 'Sarah Brown',
      email: 'sarah.brown@email.com',
      phone: '+1 234-567-8903',
      dateOfBirth: '1992-07-14',
      address: '321 Elm Street, Westside, City 12348',
      bloodType: 'AB-',
      allergies: [],
      lastVisit: '2024-01-05',
      totalVisits: 3,
      upcomingAppointments: 1,
      medicalHistory: [
        {
          date: '2024-01-05',
          diagnosis: 'Routine Physical',
          doctor: 'Dr. Sarah Johnson',
          notes: 'Annual physical completed, all results normal'
        }
      ]
    }
  ];

  const filteredPatients = mockPatients.filter(patient =>
    patient.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
    patient.email.toLowerCase().includes(searchQuery.toLowerCase()) ||
    patient.phone.includes(searchQuery)
  );

  const handleViewDetails = (patient: any) => {
    setSelectedPatient(patient);
    setShowDetailsModal(true);
  };

  const calculateAge = (dateOfBirth: string) => {
    const today = new Date();
    const birthDate = new Date(dateOfBirth);
    let age = today.getFullYear() - birthDate.getFullYear();
    const monthDiff = today.getMonth() - birthDate.getMonth();
    
    if (monthDiff < 0 || (monthDiff === 0 && today.getDate() < birthDate.getDate())) {
      age--;
    }
    
    return age;
  };

  return (
    <div className="p-6">
      <div className="mb-6">
        <h1 className="text-3xl font-bold text-gray-900 mb-2">Patients</h1>
        <p className="text-gray-600">Manage your clinic's patient database</p>
      </div>

      {/* Search and Stats */}
      <div className="mb-6">
        <div className="flex flex-col md:flex-row md:items-center md:justify-between space-y-4 md:space-y-0">
          <div className="flex-1 max-w-md">
            <Input
              placeholder="Search by name, email, or phone..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              icon={<Search size={20} className="text-gray-400" />}
            />
          </div>
          
          <div className="flex items-center space-x-6 text-sm text-gray-600">
            <div className="text-center">
              <p className="text-2xl font-bold text-gray-900">{mockPatients.length}</p>
              <p>Total Patients</p>
            </div>
            <div className="text-center">
              <p className="text-2xl font-bold text-gray-900">
                {mockPatients.reduce((acc, patient) => acc + patient.upcomingAppointments, 0)}
              </p>
              <p>Upcoming Appointments</p>
            </div>
            <div className="text-center">
              <p className="text-2xl font-bold text-gray-900">
                {mockPatients.filter(patient => {
                  const lastVisit = new Date(patient.lastVisit);
                  const thirtyDaysAgo = new Date();
                  thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);
                  return lastVisit > thirtyDaysAgo;
                }).length}
              </p>
              <p>Recent Visits (30 days)</p>
            </div>
          </div>
        </div>
      </div>

      {/* Patients List */}
      <div className="space-y-4">
        {filteredPatients.length === 0 ? (
          <Card>
            <CardContent className="p-8 text-center">
              <User size={48} className="text-gray-400 mx-auto mb-4" />
              <p className="text-gray-600">No patients found matching your search.</p>
            </CardContent>
          </Card>
        ) : (
          filteredPatients.map((patient) => (
            <Card key={patient.id} hover>
              <CardContent className="p-6">
                <div className="flex items-center justify-between">
                  <div className="flex items-center space-x-4">
                    <div className="w-12 h-12 bg-blue-100 rounded-full flex items-center justify-center">
                      <User className="text-blue-600" size={24} />
                    </div>
                    
                    <div>
                      <h3 className="text-lg font-semibold text-gray-900">{patient.name}</h3>
                      <div className="flex items-center space-x-4 text-sm text-gray-600 mt-1">
                        <div className="flex items-center space-x-1">
                          <Calendar size={14} />
                          <span>Age: {calculateAge(patient.dateOfBirth)}</span>
                        </div>
                        <div className="flex items-center space-x-1">
                          <Phone size={14} />
                          <span>{patient.phone}</span>
                        </div>
                        <div className="flex items-center space-x-1">
                          <Mail size={14} />
                          <span>{patient.email}</span>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div className="flex items-center space-x-6">
                    <div className="text-center">
                      <p className="text-lg font-bold text-gray-900">{patient.totalVisits}</p>
                      <p className="text-xs text-gray-600">Total Visits</p>
                    </div>
                    
                    <div className="text-center">
                      <p className="text-lg font-bold text-blue-600">{patient.upcomingAppointments}</p>
                      <p className="text-xs text-gray-600">Upcoming</p>
                    </div>

                    <div className="text-center">
                      <p className="text-sm text-gray-600">Last Visit</p>
                      <p className="text-sm font-medium">{new Date(patient.lastVisit).toLocaleDateString()}</p>
                    </div>

                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => handleViewDetails(patient)}
                    >
                      <Eye size={16} className="mr-1" />
                      View Details
                    </Button>
                  </div>
                </div>

                {/* Additional Info */}
                <div className="mt-4 pt-4 border-t border-gray-200">
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-sm">
                    <div>
                      <p className="text-gray-600">Blood Type</p>
                      <p className="font-medium">{patient.bloodType}</p>
                    </div>
                    <div>
                      <p className="text-gray-600">Allergies</p>
                      <p className="font-medium">
                        {patient.allergies.length > 0 ? patient.allergies.join(', ') : 'None'}
                      </p>
                    </div>
                    <div>
                      <p className="text-gray-600">Address</p>
                      <p className="font-medium">{patient.address}</p>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          ))
        )}
      </div>

      {/* Patient Details Modal */}
      <Modal
        isOpen={showDetailsModal}
        onClose={() => setShowDetailsModal(false)}
        title="Patient Details"
        size="xl"
      >
        {selectedPatient && (
          <div className="space-y-6">
            {/* Basic Information */}
            <div>
              <h4 className="font-semibold text-gray-900 mb-3">Basic Information</h4>
              <div className="grid grid-cols-2 gap-4 bg-gray-50 p-4 rounded-lg">
                <div>
                  <p className="text-sm text-gray-600">Full Name</p>
                  <p className="font-medium">{selectedPatient.name}</p>
                </div>
                <div>
                  <p className="text-sm text-gray-600">Age</p>
                  <p className="font-medium">{calculateAge(selectedPatient.dateOfBirth)} years</p>
                </div>
                <div>
                  <p className="text-sm text-gray-600">Date of Birth</p>
                  <p className="font-medium">{new Date(selectedPatient.dateOfBirth).toLocaleDateString()}</p>
                </div>
                <div>
                  <p className="text-sm text-gray-600">Blood Type</p>
                  <p className="font-medium">{selectedPatient.bloodType}</p>
                </div>
                <div>
                  <p className="text-sm text-gray-600">Phone</p>
                  <p className="font-medium">{selectedPatient.phone}</p>
                </div>
                <div>
                  <p className="text-sm text-gray-600">Email</p>
                  <p className="font-medium">{selectedPatient.email}</p>
                </div>
              </div>
            </div>

            {/* Address */}
            <div>
              <h4 className="font-semibold text-gray-900 mb-3">Address</h4>
              <div className="bg-gray-50 p-4 rounded-lg">
                <p className="text-gray-700">{selectedPatient.address}</p>
              </div>
            </div>

            {/* Medical Information */}
            <div>
              <h4 className="font-semibold text-gray-900 mb-3">Medical Information</h4>
              <div className="bg-gray-50 p-4 rounded-lg">
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <p className="text-sm text-gray-600">Allergies</p>
                    <p className="font-medium">
                      {selectedPatient.allergies.length > 0 
                        ? selectedPatient.allergies.join(', ')
                        : 'No known allergies'}
                    </p>
                  </div>
                  <div>
                    <p className="text-sm text-gray-600">Total Visits</p>
                    <p className="font-medium">{selectedPatient.totalVisits}</p>
                  </div>
                </div>
              </div>
            </div>

            {/* Medical History */}
            <div>
              <h4 className="font-semibold text-gray-900 mb-3">Recent Medical History</h4>
              <div className="space-y-3">
                {selectedPatient.medicalHistory.map((record: any, index: number) => (
                  <div key={index} className="border border-gray-200 rounded-lg p-4">
                    <div className="flex justify-between items-start mb-2">
                      <div>
                        <h5 className="font-medium text-gray-900">{record.diagnosis}</h5>
                        <p className="text-sm text-gray-600">{record.doctor}</p>
                      </div>
                      <span className="text-sm text-gray-500">
                        {new Date(record.date).toLocaleDateString()}
                      </span>
                    </div>
                    <p className="text-sm text-gray-700">{record.notes}</p>
                  </div>
                ))}
              </div>
            </div>

            {/* Actions */}
            <div className="flex justify-end space-x-3 pt-4 border-t border-gray-200">
              <Button variant="outline" onClick={() => setShowDetailsModal(false)}>
                Close
              </Button>
              <Button variant="outline">
                <FileText size={16} className="mr-2" />
                View Full History
              </Button>
              <Button>
                Schedule Appointment
              </Button>
            </div>
          </div>
        )}
      </Modal>
    </div>
  );
};
